### ISSUE TITLE
mvncp: Ruby -> Kotlin

### ISSUE THREAD

**Issue by IRus** [holgerbrandl/kscript#1]
I hope we can rewrite mnvcp with Kotlin. Because a lot machines (like default Ubuntu distribution) doesn't have ruby.

**Comment by holgerbrandl** [comment]
Indeed, relying on ruby is not a good one. As indicated in the [readme](README.md) it was just taken from https://github.com/andrewoma/kotlin-script to kickstart `kscript`. Most of `mvncp`'s complexity seems to be related to scala versioning which we don't need anyway. So a fresh implementation should be much more compact.

I'll have a look asap to replace it with a Kotlin version.

**Comment by holgerbrandl** [comment]
What do you think about `expandcp.kts`? I'm happy to merge in pull requests. :-)

**Comment by IRus** [comment]
@holgerbrandl I don't have chance to take a look closer, but it great! So fast :)
