### ISSUE TITLE
@file:DependsOn doesn't work..have to use //DEPS

### ISSUE THREAD

**Issue by kenyee** [holgerbrandl/kscript#101]
This doesn't pull in the libraries:

@file:DependsOn("com.squareup.moshi:moshi:1.5.0,com.squareup.moshi:moshi-adapters:1.5.0,com.squareup.moshi:moshi-kotlin:1.5.0"

But the older notation does work:
//DEPS com.squareup.moshi:moshi:1.5.0,com.squareup.moshi:moshi-adapters:1.5.0,com.squareup.moshi:moshi-kotlin:1.5.0

I'm using kscript 2.3 on OSX and installed by homebrew.

**Comment by holgerbrandl** [comment]
Indeed, but it is by design. With the annotations you have to provide one line per dependency. So in your case
```
@file:DependsOn("com.squareup.moshi:moshi:1.5.0")
@file:DependsOn("com.squareup.moshi:moshi-adapters:1.5.0")
@file:DependsOn("com.squareup.moshi:moshi-kotlin:1.5.0")
```

Why you may wonder? it's for compatiblity with  https://github.com/ligee/kotlin-jupyter which also supports the annotation.

**Comment by holgerbrandl** [comment]
Actually, your example worked for me. Not sure yet why it did not work for you.

But you did not use it as intended.  The annotations actually allow for multiple dependency arguments:
```
@file:DependsOn("com.squareup.moshi:moshi:1.5.0", "com.squareup.moshi:moshi-adapters:1.5.0","com.squareup.moshi:moshi-kotlin:1.5.0")
```
The fact that it worked for me is rather a bug when extracting the dependencies from your script, which will fixed.

**Comment by kenyee** [comment]
Will retry w/ next version update.  Not sure why it doesn't work either.  I'll comment again if it doesn't work and ask for tips on how to debug this (maybe a debug mode where it dumps out what it's parsing?)

**Comment by holgerbrandl** [comment]
+1 Indeed a verbose mode would be helpful for debugging problems.
