### ISSUE TITLE
--idea not usable with //INCLUDE

### ISSUE THREAD

**Issue by EugeneSusla** [holgerbrandl/kscript#103]
I really like the idea of having a dedicated `utils.kts` with common functions used by other scripts, and it's currently doable with the include directive, however if I then try to generate the `--idea` project, the file being opened is some temporary consolidated script, as opposed to a symlink to my original file as I get if I don't use includes.

I believe this can be made more useful by instead symlinking both the script and all it's included scripts recursively, while consolidating their dependencies in build.gradle. This should resolve the "red references" problem, as well as let modify both script and its dependencies all in one intellij project, making it smoother to move stuff back and forth.

I'm happy to implement and send PR if there's no objections to this approach

**Comment by holgerbrandl** [comment]
Indeed, temporary projects will be based on the pre-processed script. 

That's a tricky one fix. Either we resolve them or good code will be red in the temporary intellij project. Resolving them temporary will work for some but won't for others. Eg consider:

```
//INCLUDE ../../../foo.kt
//INCLUDE https://raw.githubusercontent.com/holgerbrandl/kscript/master/test/resources/includes/include_3.kt
```
For those ones I don't see any sensible way to create symlinks. I think we need to actually resolve them to provide a temporary project context. 
Because how would you symlink them without rewriting the user script?

I guess we could fix some cases, but an incomplete solution might be more confusing than helpful. What do you think?

**Comment by EugeneSusla** [comment]
For links, it should be ok to symlink to it's cached .kts file in ~/.kscript dir, like the one that gets created when calling kscript with that url directly.

For parent dirs in path - as long as we don't attempt to have the directory structure in src/ mimic that of the corresponding scripts we should be fine. The script and foo.kt would just be symlinked side by side in src/

So, for your example, the way I imagine it, the ~/.kscript would look something like this:
```
~/.kscript
├── kscript_tmp_project__url_cache_d8f22e323c8720a2.kts_1519196345122/
│   ├── build.gradle
│   ├── local.properties
│   └── src/
│       ├── actualScript.kts -> /tmp/1/2/3/actualScript.kts
│       ├── foo.kts -> /tmp/foo.kt
│       └── url_cache_d8f22e323c8720a2.kts -> ~/.kscript/url_cache_d8f22e323c8720a2.kts
└── url_cache_d8f22e323c8720a2.kts
```
With this approach if multiple dependencies have the same base file name, we'd have to rewrite the symlink name in some way, so that they can both be placed in src/, but otherwise I think it should be a pretty good way to handle it.

What do you think about this approach?

**Comment by holgerbrandl** [comment]
A potential issue when referencing URL cache copies is that `kscript` silently assumes URLs to be static. So changing the cached URL, will affect the local script behavior, but the user might forget to change the URL target. However, that's something we're not likely to solve, and the rest of your plan sounds solid.

I think I would ignore potential name-clashes for now.

So the actual user script would remain unchanged then? I think this would be important to avoid confusion on the user side. Intellij should resolve the dependencies internally nevertheless if all imports are located in the `src` directory. 

It would be great if you could help implementing that feature.

**Comment by EugeneSusla** [comment]
Perhaps the stale url cache issue can be solved by kscript also maintaining a symlink mapping a url to it's last downloaded cache, like:
`~/.kscript/urlcache/https/raw.githubusercontent.com/holgerbrandl/kscript/master/test/resources/includes/include_3.kt -> ~/.kscript/url_cache_d8f22e323c8720a2.kts`. Then we could simply link to that instead when creating project, sparing the user from having to ever manually update it.

> So the actual user script would remain unchanged then?

Yes, we won't be modifying the user script - that would indeed be confusing. Just symlinking to it and its includes from the `src/` directory

I'll start working on this then

**Comment by holgerbrandl** [comment]
Not sure if I understand this correctly. How would this cache differ from the current one, where we download and cache an url the first time `kscript` detects it in an import statement, and keeps the cached copy until the user clears the cache with `--clear-cache`?

I'd suggest to keep the caching as it is for now and just point the URL caching behavior out in the docs. For truely robust dependencies users could and should use `@file:DependsOn anyway`. 

Looking forward to your PR. :-)

**Comment by EugeneSusla** [comment]
Never mind the caching thing - I misunderstood the hash in the name to be of the contents instead of of the url itself.
