### ISSUE TITLE
Illegal reflective access warning

### ISSUE THREAD

**Issue by cplerch** [holgerbrandl/kscript#106]
When running a packaged kscript with

```
java version "9.0.4"
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)
```
I get these warnings befor the normal output:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/mnt/c/_/dev/ws/temp/kscriptlet.kscript1.jar) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by holgerbrandl** [comment]
The problem here is that [capsule](https://github.com/puniverse/capsule ) framework used for packaging is not compatible yet with the more restrictive reflection model in java9. The offending line is https://github.com/puniverse/capsule/blob/master/capsule/src/main/java/Capsule.java#L5564

The corresponding ticket seems to be https://github.com/puniverse/capsule/issues/115

Once a corrected caspule version has been released we will start using it. Until then I'm not really sure about how to address it.

**Comment by cplerch** [comment]
Thanks, no problem for me - can easily switch to Java8, hoping it will work
there as expected.
Regards, Chris

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virenfrei.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

2018-03-01 0:33 GMT+01:00 Holger Brandl <notifications@github.com>:

**Comment by cplerch** [comment]
I have now reverted back to Oracle Java8 on Ubuntu 16.04 LTS:
```
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

```
and executing a script with
`kscript myscript.kts`
works fine.
However, when trying to package any script I get:
```
[kscript] Packaging script 'kscriptlet.6a72c5d1b3f821b7' into standalone executable...
[kscript] Finished packaging into /mnt/c/_/dev/ws/temp/kscriptlet.6a72c5d1b3f821b7
[kscript] [ERROR] packaging of 'kscriptlet.6a72c5d1b3f821b7' failed:

```
without any further error description after "failed:"

**Comment by holgerbrandl** [comment]
Logging was indeed a bit misleading, but corrected already (see commit).

Not sure what went wrong. Could you provide an example? To debug yourself what goes wrong, clear all data under `~/.kscript`, rerun the package command, locate the temporary gradle project used for packaging under `~/.kscript/kscript_tmp_project__<SOME_HASH_OF_YOUR_SCRIPT>`, cd to the dir and run `gradle simpleCapsule` manually to see what goes wrong.

**Comment by LanderlYoung** [comment]
Same issue tome. 
Tried to package it up. `kscript --package ktd.kts`

WON'T RUN with java 10.
```bash
$./ktd
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by Capsule (file:/Users/young/Desktop/ktd) to field com.sun.jmx.mbeanserver.JmxMBeanServer.mbsInterceptor
WARNING: Please consider reporting this to the maintainers of Capsule
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
ktd: missing URL operand
```

```bash
$java -version
java version "10.0.2" 2018-07-17
Java(TM) SE Runtime Environment 18.3 (build 10.0.2+13)
Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.2+13, mixed mode)
```

source code here https://gist.github.com/LanderlYoung/b64a0f25cd9d6fe6823d1209a25d9de7/edit

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to reopen if needed.

**Comment by eygraber** [comment]
3 years later and this is still an issue. Is there any way to use a tool other than capsule (which appears to be dead)?

**Comment by holgerbrandl** [comment]
Feel welcome to suggest some more current option. I'm not using this feature myself.
