### ISSUE TITLE
Compile errors with 1.8 targetted code

### ISSUE THREAD

**Issue by yschimke** [holgerbrandl/kscript#114]
Trying to ditch my own internal Kotlin script usage with kscript

https://github.com/yschimke/oksocial-scratchpad/pull/1/files

Getting this error when running from a command line

```
$ ./src/main/kotlin/commands/giphysearch.kts trump
[kscript] [ERROR] compilation of './src/main/kotlin/commands/giphysearch.kts' failed
src/main/kotlin/commands/giphysearch.kts:17:21: error: cannot inline bytecode built with JVM target 1.8 into bytecode that is being built with JVM target 1.6. Please specify proper '-jvm-target' option
  val urls = client.query<SearchResults>(
                    ^
```

**Comment by holgerbrandl** [comment]
The kotlin default target is still 1.6. to compile against 1.8 you need to
provide the compiler flag via  //Compile_Opts or the corresponding
annotation. See readme.

Yuri Schimke <notifications@github.com> schrieb am So., 25. März 2018,
09:47:

**Comment by yschimke** [comment]
Is there a real annotation behind file:CompilerOpts, it is flagged as red in Intellij, while DependsOn comes from import org.jetbrains.kotlin.script.util.DependsOn

```
@file:DependsOn("com.baulsupp:oksocial:1.37.0")
@file:CompilerOpts("-jvm-target 1.8")
//COMPILER_OPTS -jvm-target 1.8
```

**Comment by yschimke** [comment]
n.m. found 

    implementation 'com.github.holgerbrandl:kscript-annotations:1.2'

**Comment by holgerbrandl** [comment]
It's added by default when using annotations in a script processed by kscript. Not sure what `org.jetbrains.kotlin.script.util.DependsOn` is all about, I'm seeing it for the first time.
