### ISSUE TITLE
Deploy as snap

### ISSUE THREAD

**Issue by reitzig** [holgerbrandl/kscript#115]
GNU/Linux users can install Kotlin with `snap` nowadays. It would be convenient if `kscript` could be installed in the same way.

**Comment by holgerbrandl** [comment]
Isn't sdkman enough?

If not, how can we do so?

**Comment by reitzig** [comment]
I've never come across sdkman before, but snap is also rather new. No idea how the two compare. I know that Canonical drives snap and Ubuntu will ship with it pre-installed.

I guess one would have to use the same for both Kotlin and kscript so the connection plays out well?

The how is supposed to be simple: https://docs.snapcraft.io/build-snaps/your-first-snap
I haven't done it myself; I'm sure there are devilish details. If I get around to digging into it I'd be happy to provide a pull request, but don't hold your breath. :'D

**Comment by holgerbrandl** [comment]
Since it is ubuntu specific, I'm looking forward to your PR.

**Comment by reitzig** [comment]
It's not specific to Ubuntu; most if not all of the major distributions are supported, cf [here](https://snapcraft.io/). Anyway, fair enough! If I figure out the details of snaps I'll try to cook something up.

**Comment by reitzig** [comment]
sdkman seems to be the more appropriate channel for something like kscript.

**Comment by Wavesonics** [comment]
One big advantage of a snap is that it can install globally, for all users on the system. I looked a little, and it didn't look like there was a nice easy way to use SDK Man to do that. With Kotlin and Kscript both being snaps, you could provide all users on your system this functionality.

**Comment by holgerbrandl** [comment]
Not arguing against snap (still welcoming a PR here) but just in defense of sdkman, it also supports global installs, see https://sdkman.io/install and https://serverfault.com/questions/732025/how-do-i-install-groovy-on-an-ubuntu-system-for-all-users
