### ISSUE TITLE
kscript breaks when environment includes JAVA_OPTS for debugging

### ISSUE THREAD

**Issue by ivoanjo** [holgerbrandl/kscript#123]
Hello there, and thanks for your awesome work on kscript :tada:

Recently I was trying to debug a kscript script, and to do so I had set on my environment

```bash
$ export JAVA_OPTS="-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
```

Unfortunately, this breaks kscript:

```bash
$ kscript test.kts 
.sdkman/candidates/kscript/current/bin/kscript: line 28: exec: Listening: not found
``` 

This is because in <https://github.com/holgerbrandl/kscript/blob/v2.4.1/kscript#L28> the result of the JVM invocation is `exec`'d, but when using the above `JAVA_OPTS`, the JVM always outputs the following message

```
Listening for transport dt_socket at address: 5005
```

which breaks the `exec`. My very crude hack to fix it was just grepping it away (below), but there's probably a less hackish way of going about this.

```bash
eval "exec $(kotlin -classpath ${jarPath} kscript.app.KscriptKt "$@" | grep -v 'Listening for transport dt_socket at address')"
```

Thanks!

**Comment by holgerbrandl** [comment]
What about `quiet=y`? see https://stackoverflow.com/questions/48431989/suppress-listening-for-transport-dt-socket-message-when-remote-debugging-java

**Comment by ivoanjo** [comment]
I tried to search for that one, but clearly your googling skills are better than mine :)

Feel free to close the ticket!

**Comment by holgerbrandl** [comment]
You're welcome! :-)
