### ISSUE TITLE
Having trouble to use kscript in enterprise environment when package

### ISSUE THREAD

**Issue by yhjhoo** [holgerbrandl/kscript#129]
I have got following error when use --package

```
* What went wrong:
Plugin [id: 'us.kirchmeier.capsule', version: '1.0.2'] was not found in any of the following sources:
```
I have tried with my personal mac and it works fine, this error happened on my company's mac. Is it cos by the firewall? Do you need to setup proxy?

**Comment by holgerbrandl** [comment]
Can you access jcenter via maven/gradle in your environment?

**Comment by yhjhoo** [comment]
Seems not able to. We have an internal maven host.

**Comment by holgerbrandl** [comment]
So do you think proxy support should/could be added to kscript. If so, how would we want to do it?

**Comment by holgerbrandl** [comment]
Closed because of inactivity. Feel welcome to reopen/comment on this thread in case it's still an issue for you.

**Comment by inktomi** [comment]
It would be great if we had a set of things like `@file:ProxyUrl` `@file:ProxyPort` etc etc that would apply to the script's repositories when ran, or something similar.

**Comment by holgerbrandl** [comment]
I'm not entirely sure, but I think this could be configured in the user-gradle settings in ~/.gradle. These settings are respected when running packaging mode (because gradle is simply used under the hood)
