### ISSUE TITLE
Non-jcenter dependecies are not resolved

### ISSUE THREAD

**Issue by vivus-ignis** [holgerbrandl/kscript#132]
Hi,
I'm trying to run this script
```kotlin
#!/usr/bin/env kscript

@file:MavenRepository("maven-central","http://central.maven.org/maven2/")
@file:DependsOnMaven("javax.jms:jms:1.1")
@file:DependsOnMaven("org.apache.activemq:activemq-all:5.15.4")

import javax.jms.Session
 
import org.apache.activemq.ActiveMQConnectionFactory
```

And here is what I have as a result

[kscript] Resolving dependencies...Failed to lookup dependencies. Maven reported the following error:
[ERROR] Failed to execute goal on project maven_template: Could not resolve dependencies for project kscript:maven_template:jar:1.0: Failed to collect dependencies at org.apache.activemq:activemq-all:jar:5.15.4: Failed to read artifact descriptor for org.apache.activemq:activemq-all:jar:5.15.4: Could not transfer artifact org.apache.activemq:activemq-all:pom:5.15.4 from/to jcenter (http://jcenter.bintray.com/): /home/ignis/.m2/repository/org/apache/activemq/activemq-all/5.15.4/activemq-all-5.15.4.pom.part.lock (No such file or directory) -> [Help 1]

If I remove a file:MavenRepository line, the result is exactly the same.

Kscript v2.4.4, Kotlin 1.2.50, both installed with sdkman.

**Comment by holgerbrandl** [comment]
Your example works/runs correctly for me. 

What is you version of Maven? Mine is
```
# mvn --version
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T21:39:06+02:00)
Maven home: /Users/brandl/.sdkman/candidates/maven/current
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_162.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.4", arch: "x86_64", family: "mac"
```

Are you sitting behind some kind of firewall (i.e. requiring a proxy)?

**Comment by vivus-ignis** [comment]
Thank you for replying.

```
mvn --version
Apache Maven 3.5.3 (3383c37e1f9e9b3bc3df5050c29c8aff9f295297; 2018-02-24T20:49:05+01:00)
Maven home: /home/ignis/.sdkman/candidates/maven/current
Java version: 1.8.0_161, vendor: Oracle Corporation
Java home: /home/ignis/.sdkman/candidates/java/8u161-oracle/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.14.48-2-manjaro", arch: "amd64", family: "unix"
```

Strangely enough, I've just wiped out my .m2 directory and now, after fetching everything from scratch, it somehow just works. I should probably blame poisoned maven cache.

**Comment by vivus-ignis** [comment]
I think it was docker creating files in .m2 as a root user (I was mounting ~/.m2 into a container). I had to use 'sudo' to delete .m2 directory's contents.
