### ISSUE TITLE
Is it possible to have something like unix 'exec'

### ISSUE THREAD

**Issue by oshai** [holgerbrandl/kscript#134]
I would like my script to do some calculations and eventually run another shell command instead, ideally even save it in bash history.
Is there a way to do that?

**Comment by holgerbrandl** [comment]
I don't think that you can do process substitution in the jvm. See https://askubuntu.com/questions/525767/what-does-an-exec-command-do for a nice intro
You can mimic certain aspects of it via https://stackoverflow.com/questions/33781012/using-stdin-in-java-process-builder

For sure you invoke `bash` from java/kotlin/kscript. See https://git.io/fSGgU or https://github.com/holgerbrandl/kutils/blob/master/src/main/kotlin/de/mpicbg/scicomp/kutils/Bash.kt for an actual public artifact.

Not sure if/how commands evaluated in this way could/would be added to the history.
