### ISSUE TITLE
RFE: Upgrade kotlin version to 1.2.51, allow persisting build directories

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#139]
Recommend upgrading to kotlin 1.2.51 
Intellij has fixed many bugs in the kotlin script usage in their IDE.  

I would like the ability to (easily) 'persist' the temporary build directory trees created when using the package and ide features.

My use case is to have a minimal source tree with kscript only sources (mabye a minimal build.gradle), and be able to create the runtime packing via a build script.

Example   
   kscript --perist --package  myscript.kts

Does the same as --package except for NOT running build and NOT deleting the directory.
Which directory? Good question.  Perhaps
  kscript --persist-build-dir  <myscriptbuilddir> --package myscript.kts
and analogous
  kscript --persist-build-dir  <myscriptbuilddir> --idea myscript.kts

Alternate  --no-delete-build-tree ,  --no-launch-ide and --no-build-package  options

**Comment by holgerbrandl** [comment]
Actually nothing is deleted, all the directories pile up under `~/.kscript`. 

So what would be  the  motivation to reuse a build dir? The only aspect I could think of is performance, but is it really that slow?

**Comment by DALDEI** [comment]
Motivation: see other RFE.  So I can debug it along side existing projects, so I can make minor changes to the build.gradle such as using includedBuilds features,  so I can link it as a sub-project of a bigger projects.

**Comment by holgerbrandl** [comment]
Let's close this ticket then and focus on the others. :-)
