### ISSUE TITLE
RFE: API for loading compiled (or not) kscript files into a running kotlin program

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#140]
I am embedding kotlin scripts into a bigger program.  I would like to be able to re-use the features of kscript but via a kotlin (or java) API.  I am currently using the native kotlin JSR-232 APIs to compile and run kotlin scripts.  It is very tedious, changes without warning and hair pulling to figure out. Once I did, what I discovered is that it is not interoperable with how kscript behaves.  I cannot use kscript to develop a script and then reuse that script embedded in a larger program.  Issues include the script template handling, argument passing, the //XXXX  and @file annotations etc. (i.e. all the good stuff). The most perplexing to me is the classpath handling and dependency resolution.  I have yet to devise a method of injecting the right dependencies and have it actually work reliably.   The equivalent code in the kotlin source relies on private classes in intellij that are not available publicly.  I gave up when I ran into magic jar file who's source is not public.   

For now I have to use different versions of the scripts if I want run with kscript or embedded. 
A compromise would be to be able to use kscript to 'compile' the scripts or atleast do the heavy lifting of resolving dependencies, adding imports etc producing a more portable script format (less readable but more usable embedded).   I do not want to require the full kotlin and maven installation at runtime, so either omitting those features or pre-processing for them would be a compromise.

Ideally one might arise at the situation where the difference between 'compiled kotlin source' and 'dynamic kscript' is blurred and irrelevant -- leaving the only significant difference a matter of performance and dependency tradoffs.  It would be appealing to be able to develop quickly in kscript then as functionality matures migrate the code into the compiled baseline without having to change it.
Similarly, as needed extract kotlin.kt source as kscript.kts snippets where runtime script flexability is needed without having to write a proxy or wrapper layer to marshal requests through the scripting layer.
I can dream right ?

**Comment by holgerbrandl** [comment]
If I understand you correctly, we would want to implement a kscript version of the kotlin scripting API, see https://github.com/Kotlin/KEEP/blob/scripting/proposals/scripting-support.md#proposal

This would also ease IDE integration a lot, and seems like a great IDE. 
I'm not sure how to deploy such an api outside of the IDE though?

**Comment by DALDEI** [comment]
I dont know how to do it *IN* the IDE :) As of very recent (2 weeks?)  Intellij is much better about running scripts -- but not kscripts yet :) 
Not sure if what Im thinking is the same as you are ... but try this.
Given a kscript, you can currently build a runnable package.  by crashing the build at the right point I got the build.gradle to stay (see other RFE).  That showed that the full set of dependencies and the compiled kscript were all present as 'normal class files'.   At that point 'simply' loading the class file into a normal program and loading the magic main class and passing it the magic args 'should just work'.

So from a 'excersize to the reader' -- it should be trivial to make that into a 'idea module' or 'gradle sub project' like any  other., along with whatever startup glue is needed (find jar, load class, run) - voila. 

It wont run 'as a kotlin script' from IDEA as you are doing things the IDE doesnt know, but the produced bits should be debugabble.  If  one made a kscript gradle plugin that ran the equivilent of a kscript compile then it might even be picked up by IDEA? (like a pre-processed source)

**Comment by holgerbrandl** [comment]
> Given a kscript, you can currently build a runnable package. by crashing the build at the right point I got the build.gradle

Why don't you rather run it with `--idea`. No need to crash it here.

A kscript plugin is the next step. I just need find time to do it, or get some help from the community. The scripting API is a rather new API and will have some hidden glitches.

**Comment by holgerbrandl** [comment]
Closed in favor of #148
