### ISSUE TITLE
feature: Add credentials to @file:MavenRepository

### ISSUE THREAD

**Issue by MikeMitterer** [holgerbrandl/kscript#143]
I'm using Artifactory for my Maven-Repo
In my case the repo needs credentials

Would be cool if I could specify them for @file:MavenRepository

**Comment by holgerbrandl** [comment]
Is there a public maven repo with credentials support which we could use for testing?

**Comment by MikeMitterer** [comment]
Not that I know - can I test something for you?

**Comment by stephenbyrne-mfj** [comment]
Hard-coding credentials in a script is probably a Bad Idea. You can put your credentials in `~/.m2/settings.xml`:

    <?xml version="1.0"?>
    <settings>
        <servers>
            <server>
                <id>{the ID from the @file:MavenRepository}</id>
                <username>azurediamond</username>
                <password>hunter2</password>
            </server>
        </servers>
    </settings>

This works today, I just tested it on master.

**Comment by holgerbrandl** [comment]
I'd also think that credentials should better go into config file as described above, but it would be a technically easy to extend the annotation to accept credentials. Doing so would also help to see if  #49 could provide a better solution for dependency resolution.

@ligee Are you planning to add credential support to `@file:Repository` as used in https://github.com/Kotlin/KEEP/blob/master/proposals/scripting-support.md#script-with-maven-dependencies-resolving-support ?
