### ISSUE TITLE
kscript comment-style directives are marked as errors with ktlint

### ISSUE THREAD

**Issue by 0legg** [holgerbrandl/kscript#153]
As of https://github.com/shyiko/ktlint/issues/198, ktlint marks comments not starting with space as an error. kscript, on the other hand, is unable to parse the directive starting with space.

I'm not sure whether this issue belongs to ktlint of kscript though — my gut feeling is it's kscript who needs to adopt the change, but I'll cross-create tickets in both repos.

Ref https://github.com/shyiko/ktlint/issues/273

**Comment by 0legg** [comment]
Nope, they can't, wih the small exception like tab/spacing settings. ktlint is intentionally made strict and opinionated about style (https://github.com/shyiko/ktlint/issues/21 for more comments and background).

If, for example, kscript will support directives in the format `//\s*CODE`, it'll resolve the issue for both.

**Comment by holgerbrandl** [comment]
IMHO a linter for which specific rules can't be modified or disabled is not yet ready for primetime.
Why don't you use annotation driven config instead? Comment directives are the old approach, which will be eventually deprecated.

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to keep commenting on this thread/
