### ISSUE TITLE
Expose 'Main_<className>' entrypoint for building executable kts files

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#157]
I am attempting to incorportate kscript and .kts compatible build in Gradle.
I have not *yet* found a way to do this fully but Im close. 
The current stumbling block is how to run a compiled .kts file that works with both kscript and gradle.
When using kscript --package a main is created on the fly and the source is disposed -- 

extracting the class files from the built package I seee this 👍 
```

public final class Main_Getprops$Companion {
  public final void main(java.lang.String[]);
  public Main_Getprops$Companion(kotlin.jvm.internal.DefaultConstructorMarker);
}

```

This corresponds to the source generated in Kscript.kt
To emulate the equivalent of "kscript file.kts" or "kscript --package .. ; ./file" I belive I need to incorporate this wrapper (or maybe specify a different template ???)

**Comment by DALDEI** [comment]
I was finally able to create a standalone build that works in intellij, via 'gradle run',  and 'kscript src/main/kotlin/file.kts'  
In intellij this works directly with  (select Getprops.kts) Right Click-> Run... 


Steps: 

build.gradle ( edited, YMMV) 

```
buildscript {  
    repositories {  
       jcenter()  
    }   
}  
plugins {
  id 'org.jetbrains.kotlin.jvm' version '1.2.60'
}
dependencies {
  repositories {
jcenter()
    maven {
        url 'file:<local-maven-directory>'
    }   
  }
}
apply plugin: 'kotlin'

apply plugin: 'java'
apply plugin: 'application'
mainClassName='MainKt'
dependencies {
    compile "org.jetbrains.kotlin:kotlin-script-runtime" // needed ???
    compile "com.github.holgerbrandl:kscript-annotations:1.2"
  
}
```


src/main/kotlin/Main.kt //(NOT  Main.kts)
```

fun main(args: Array<String>){
 val script = Getprops::class.java.classLoader.loadClass("Getprops")
   script.getDeclaredConstructor(Array<String>::class.java).newInstance(args)
}
```

src/main/kotlin/Getprops.kts
```

#!/home/dlee/bin/kscript    # helper script file, can use #!/usr/bin/env kscript --script 
//IMPORT Main.kt             // Not Needed ???
@file:MavenRepository("localrepo","file:/path/to/local/repo")

@file:DependsOn("local built module : x : x ")


object Properties: Table(name="properties") {
  val name = varchar("name",256).primaryKey()
  val value = varchar("value", 256)
}
fun main(args:Array<String>){
... normal kts code
  }
}

main(arrayOf())   // Needed to run main() via kscript 
```

**Comment by holgerbrandl** [comment]
Why don't you use a kt-file as input? There you could define your main entry point yourself, see https://github.com/holgerbrandl/kscript#use-entry-to-run-applications-with-main-method

Imho this solves your problem.

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to keep commenting on this thread.
