### ISSUE TITLE
How will kotlin 1.3 scripting affect kscript?

### ISSUE THREAD

**Issue by jangalinski** [holgerbrandl/kscript#168]
Just read the [RC release notes](https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-3-rc-is-here-migrate-your-coroutines/) and stumbled upon:

_There is a new public artifact: kotlin-main-kts. It contains a script definition and a minimal maven artifacts resolver in a single jar. Its purpose is to simplify the creation and usage of the simple utility scripts that may depend on the external libraries. For example, you can now write the following script:_

```
@file:Repository("https://jcenter.bintray.com")
@file:DependsOn("org.jetbrains.kotlinx:kotlinx-html-jvm:0.6.11")
​
import kotlinx.html.*
import kotlinx.html.stream.*
​
print(createHTML().html {
    body {
        h1 { +"Hello, World!" }
    }
})
```

_Then run it with only kotlin-main-kts.jar in the classpath:_

`kotlinc -cp <path/to/kotlin-main-kts.jar> -script sample.main.kts`

This looks a lot like what kscript currently does ... will you adopt the 1.3 scripting? Will this make kscript obsolete? Is this taking kscript to the core? What are your thoughts?

**Comment by oshai** [comment]
I had the same question myself

**Comment by holgerbrandl** [comment]
Excellent question. Clearly there's quite some overlap. I'm actually superhappy that scripting makes such a big leap forward with 1.3.

I'm already in contact with @ligee, and we will investigate if/how some aspects of `kscript` could be merged into the scripting part of the core platform.

**Comment by jangalinski** [comment]
yeah, I just saw that you where part of the discussion for scripting for quite a while: https://github.com/Kotlin/KEEP/issues/75#issuecomment-325268326

really looking forward to this ...

**Comment by holgerbrandl** [comment]
@moisesvs are there any issues when using kscript along with kotlin v1.3?[](url)

**Comment by moisesvs** [comment]
Yes. When I am creating a new project with --package option. I open the project with IntelliJ to change the kotlin version to 1.3 (this changed is done into build.gradle) 

```
plugins {
    id "org.jetbrains.kotlin.jvm" version "1.2.0"
}
```

and I obtain the following error:

Unable to load class 'org.gradle.api.attributes.HasAttributes'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by CaelumF** [comment]
Partially related to #192 

I have more free time to contribute to that now :)

**Comment by holgerbrandl** [comment]
@CaelumF @moisesvs Doesn't the problem rather point towards gradle and the ide. It doesn't seem to be a problem with kscript itself, but I may miss the point here.
