### ISSUE TITLE
Better support for using kscript as a library

### ISSUE THREAD

**Issue by stephenbmfj** [holgerbrandl/kscript#177]
I want to use kscript to launch Kotlin scripts from a JVM process. I want the kscript launcher to be in process. I could just call `main` with the appropriate arguments, but it would be nicer to have a cleaner API call that also gave access to the stdin/stdout/stderr streams.

**Comment by stephenbyrne-mfj** [comment]
I am working on this, and will submit a PR.

**Comment by holgerbrandl** [comment]
Sounds great to me. Maybe we/you could a basic unit test to explain the usage as a library?

Not sure might possibly relate to a convergence with the official scripting API (@ligee).
