### ISSUE TITLE
Take jcenter out of build.gradle.kts

### ISSUE THREAD

**Issue by stephenbyrne-mfj** [holgerbrandl/kscript#178]
IMHO build scripts should not attempt to configure upstream repositories. These should be configured in `~/.gradle`.

People who want/need to use a private repository/cache should be able to set that up in `~/.gradle` and not have to modify the `build.gradle.kts` just to build.

**Comment by holgerbrandl** [comment]
I'm not sure if understand the intent correctly. Without jcenter as dependency-repo  kscript won't build, so what do we gain by forcing users to declare it in `~/.gradle` instead?

Imho declaring `repositories` in a gradle-build file is good and accepted practice. See https://docs.gradle.org/current/userguide/declaring_repositories.html

**Comment by stephenbyrne-mfj** [comment]
I did not realize this is accepted/encouraged Gradle practice.

I will go complain on the Gradle forums instead.
