### ISSUE TITLE
kshell launcher fails in presence of `@file:Include`

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/kscript#179]
Reported by @seanabraham 

Also, it looks like the current implementation fails to resolve @file:Include lines currently because the files don't exist relative to the tmpfile that's created with the kshell headers. I can put up a PR to fix that if you want, but there would be a bit more work required in recursively parsing all the included files for @file:DependsOn annotation. Alternatively, we could assume everything was depended on in the top level file and just ignore the @file:Include annotations.

**Comment by holgerbrandl** [comment]
Wouldn't it be sufficient to create the temporary script file next (that is in the same directory) to the argument script file (e.g. as a hidden file)?

**Comment by seanabraham** [comment]
Yup! I think that would work, it should be pretty simple, I can put up a PR with one such solution if you'd like (I made the changes locally already)

**Comment by seanabraham** [comment]
Although, now that I think of it, _just_ moving the file won't be enough because even though the `@file:Include` lines will technically work now, the included code will need to be stripped of actual code too

**Comment by holgerbrandl** [comment]
The code stripping as done in the current version is actual just a quick attempt of mine to allow spawning a shell even in case of syntax errors in the script. It has no other functional relevance.

So maybe we could simply strip code just in the actual argument script (as it is done now) and leave the include-documents as they are? IMHO this seems sensible since `Include`s should be syntactically correct (otherwise they are no valid includes yet, aren't they?).

**Comment by holgerbrandl** [comment]
I don't think so. In preparation for the compile-step `kscript` is creating a new script where all includes are inlined.

However, I may be wrong, so having a more specific example would be certainly helpful here.

**Comment by holgerbrandl** [comment]
Closed because of inactivity. Feel welcome to reopen if needed. Might also be obsolete.
