### ISSUE TITLE
Feature: Verbose mode

### ISSUE THREAD

**Issue by egor-n** [holgerbrandl/kscript#183]
I am currently trying to run a script from a URL via kscript and it doesn't seem to work for some reason.

Nothing gets printed to the terminal in my case so it be nice to have a `-v` mode.

**Comment by holgerbrandl** [comment]
kscript will/should already log operations like dependency resolve, and will also log on any error. Would you mind sharing the script (or some cut-down version of it)?

**Comment by egor-n** [comment]
Figured it out – nothing to do with the URL.

The file was `.kts` but it included the `fun main(args: Array<String>)` function. After renaming it to `.kt` all worked fine 👍 

Which version of the script should already log the operations? Running `kscript test.kt` where `test.kt`:

```kotlin
@file:DependsOn("com.xenomachina:kotlin-argparser:2.0.7")

fun main(args: Array<String>) {
  println("printed")
}
```

doesn't print anything but "printed" to the terminal.

**Comment by egor-n** [comment]
Ah, I see, the dependency has already been resolved. If I change the version then it prints `[kscript] Resolving dependencies...Done` too.

**Comment by holgerbrandl** [comment]
You can also run regular `kt` files with a main, but to make this work with kscript the file extension is expected to be `kt`.
