### ISSUE TITLE
Using @file:CompilerOpts("-jvm-target 1.8") doesn't work for --idea

### ISSUE THREAD

**Issue by jsonbrooks** [holgerbrandl/kscript#188]
running kscript --idea some_script.kts doesn't put the option in the gradle build file for the resulting temporary project.

**Comment by holgerbrandl** [comment]
It's unlikely that we can implement a mirroring of all possible compiler options onto gradle settings. Feel provide to provide a PR at least the most common one, which is indeed the jvm target.
