### ISSUE TITLE
kscript --idea outdated Kotlin version

### ISSUE THREAD

**Issue by CaelumF** [holgerbrandl/kscript#192]
The gradle build file created with `kotlin --idea [file.kt]` is as follows:

```groovy
plugins {
    id "org.jetbrains.kotlin.jvm" version "1.2.70"
}

repositories {
    mavenLocal()
    jcenter()

}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib"
    compile "org.jetbrains.kotlin:kotlin-script-runtime"

}

sourceSets.main.java.srcDirs 'src'
```
Is this version a fixed value? Is there a reasonable way of obtaining the latest stable version or prompting the user?

Perhaps raises the question of which Kotlin compiler version kscript should use ever. Would love to PR and work on this :)

**Comment by holgerbrandl** [comment]
Indeed we used a fixed value here at the moment.

kscript is using the installed kotlin (which must be present in `PATH`) to compile scripts.

I guess a better way to do it, would  be to infer the version from the compiler and use it instead. Feel welcome to contribute a PR. To prevent regression it would be super-awesome if you could also create a corresponding unit test as well (see `test_suite.sh` for examples).

**Comment by CaelumF** [comment]
Sounds good. I will clone and have a look around.

**Comment by CaelumF** [comment]
Hi,

What do you think of this approach?
- [ ] Create test to check after Gradle build, Kotlin plugin is installed and its version matches the local Compiler's version from `PATH`
- [ ] Create test to check Kotlin 
- [ ] Modify AppHelpers.kt to pass above tests

**Comment by holgerbrandl** [comment]
I was rather thinking to infer it directly from the PATH. E.g. by parsing it from `kotiln -version`. This would match the user intention/environment better I think.

**Comment by DALDEI** [comment]
Q: What is the 'expected state' of --idea flag ?
I have yet to be successful in actually using IntelliJ for a .kts script effectively.
The very basics work but as soon as I add a dependant jar intellij starts giving me errors on the import statements needed.
I havent debugged heavily - first wondering if its expected to work (with minimal user intervention).
of the many times Ive thought "Id like to use a kts/kscript file for ..."  -- after 20 minutes remember how painful it is and just make a 'plain' kotlin project.   

Note: by 'painful' : I mean in general, for any but the most basic scripts/kotlin -- figuring out the dependant libs, imports and correct classes/spelling/methods etc is just too much work without the IDE and decent auto-suggest --
Exactly the reason I would *want* to use kscript (to avoid all that) tends to be the same use cases that its a total pain TO use it --  
Possibly this is mitigated by using the newer features for supplying your own headers / 'DSL' etc --
But then its a matter of those not yet existing -- and to make them -- same problem.
Maybe a kind of repository for community-added 'quick script' plugins might be a solution.
where one could say add a '--with mysql' arguement to pull in the dependendencies and headers and imports for a typical mysql/jdbc kscript -- (s/mysql/a few million other great templates/)

**Comment by DALDEI** [comment]
(*IDEA*) (pun not intended) -- this is potentially a useful 'plugin' concept for kotlin in general -- not just idea or kscript or kts dependant.   analogous to extending the 'gradle init --language'  to produce 'boilerplate' builds (and for kscript -- the equivalent DSL headers) for a simple one-off project that needs to 'do XXX'  -- like the text processing module.

**Comment by holgerbrandl** [comment]
`--idea <script>` should open intellij and bootstrap a project from your script. Internally it's creating a temporary gradle file.

Your second comment about http4k is more about dependency management. I'm not sure if there would be a generic solution to that problem without adding a myriad of cli parameters (with version arguments for stability).

**Comment by krzema12** [comment]
Related: [Not unified support for KTS files](https://youtrack.jetbrains.com/issue/KT-32998).

Ideally, there should be no need to use the `--idea <script>` approach - IDEA should understand the KTS files and provide appropriate support. The issue I linked tackles a bit different problem than discussed in this issue, but there's some overlap for sure.

**Comment by holgerbrandl** [comment]
@krzema12 I agree it should be supported by the platform directly. Feel welcome to file a ticket under https://youtrack.jetbrains.com/issues/KT and crossref it in here so that we can upvote it.

**Comment by holgerbrandl** [comment]
Closed because of being inactivity for too long. Feel welcome to reopen if needed.
