### ISSUE TITLE
Support for tests

### ISSUE THREAD

**Issue by brunodles** [holgerbrandl/kscript#207]
Would be great to write tests for scripts.

We can execute it using some parameters
```
kscript --test filename.kts
```

Using this parameter the script could look for methods annotated with `@Test`.

**Comment by holgerbrandl** [comment]
imho this feels a bit out of the scope of kscript. What I would rather recommend is to use https://github.com/lehmannro/assert.sh to test your scripts. This is also how we test kscript itself to avoid regressions.

**Comment by brunodles** [comment]
The idea was just to provide a self-contained tests for small script. 
Also to provide a way to check out our scripts using Kotlin.

But as you said, maybe it's too much.

Thanks for the feedback.
