### ISSUE TITLE
Limit the environment scope of the script

### ISSUE THREAD

**Issue by C06A** [holgerbrandl/kscript#208]
Is it possible to set up the kscript to run the script in limited environment?
For example to do not allow the script to access file system or network communications...

**Comment by holgerbrandl** [comment]
No there is no sandbox model present or planned. 

I guess the best approach might be to block network access on system level https://unix.stackexchange.com/questions/68956/block-network-access-of-a-process

There also seems some way to restrct the jvm but these looks more clumsy, see https://stackoverflow.com/questions/25681670/disable-internet-access-for-jvm

**Comment by C06A** [comment]
I guess java.security.manager is what I was looking for.
Is it a way to run KScript with java.security.manager enabled and custom policy?

**Comment by holgerbrandl** [comment]
If you could share how you'd do it when running java, we could think about how this would translate to come `@file:KotlinOpts`
