### ISSUE TITLE
Cannot use --add-bootstrap-header for some reason

### ISSUE THREAD

**Issue by GuiCoppini** [holgerbrandl/kscript#209]
I wrote a simple .kts containing a `println("Hello, world")` and I wanted to test the `--add-bootstrap-header` argument/option.
As soon as I commit the command `kscript --add-bootstrap-header test.kts`, the response I get is the default "Help" screen.
![image](https://user-images.githubusercontent.com/26307771/51556080-47b13400-1e60-11e9-98fb-07d556993a79.png)

I'm with Ubuntu 18.04. Is there something I'm missing?
Thanks in advance!

**Comment by holgerbrandl** [comment]
Works for me using the current v2.7

**Comment by GuiCoppini** [comment]
Thanks! Worked using v2.7!
