### ISSUE TITLE
Permission denied with 2.7.0

### ISSUE THREAD

**Issue by twyatt** [holgerbrandl/kscript#213]
When installing `kscript` via:

```
sdk install kscript
```

Things worked great for version `2.6.0`, whereas I had a Kotlin script that began with the following header:

```
#!/usr/bin/env kscript
```

Unfortunately something seems to have changed, as now with `2.7.0` I'm getting the following error when I try to run Kotlin scripts:

```
/usr/bin/env: 'kscript': Permission denied
```

_(this was seen on a CI system so it is from a fresh install of `kscript`, not an upgrade)_

**Comment by holgerbrandl** [comment]
Indeed. There seems to be an issue with the sdk installation. I'll update it shortly. Meanwhile you could use sdkman to rollback to the old release.

**Comment by hho** [comment]
```
hho@hho-pc: ~/.sdkman/archives
➜ zipinfo kscript-2.6.0.zip 
Archive:  kscript-2.6.0.zip
Zip file size: 110587 bytes, number of entries: 4
drwxr-xr-x  3.0 unx        0 bx stor 18-Oct-29 10:57 kscript-2.6.0/
drwxr-xr-x  3.0 unx        0 bx stor 18-Oct-29 10:57 kscript-2.6.0/bin/
-rwxr-xr-x  3.0 unx      946 tx defN 18-Oct-29 10:57 kscript-2.6.0/bin/kscript
-rw-r--r--  3.0 unx   115212 bx defN 18-Oct-29 10:57 kscript-2.6.0/bin/kscript.jar
4 files, 116158 bytes uncompressed, 109881 bytes compressed:  5.4%

hho@hho-pc: ~/.sdkman/archives
➜ zipinfo kscript-2.7.0.zip 
Archive:  kscript-2.7.0.zip
Zip file size: 4520105 bytes, number of entries: 4
drwx---     6.3 fat        0 bx stor 19-Feb-16 14:37 kscript-2.7.0/
drwx---     6.3 fat        0 bx stor 19-Feb-16 14:43 kscript-2.7.0/bin/
-rw-a--     6.3 fat     1036 bx defN 19-Feb-16 14:43 kscript-2.7.0/bin/kscript
-rw-a--     6.3 fat  5063813 bx defN 19-Feb-16 14:43 kscript-2.7.0/bin/kscript.jar
4 files, 5064849 bytes uncompressed, 4519463 bytes compressed:  10.8%

```
It seems the 2.7.0 file was created on Windows, so the ZIP doesn't contain unix permissions.

The 2.7.0 release is also 43× the size of the previous one!

**Comment by dharrigan** [comment]
Ouch! That has bit me today as well!

**Comment by holgerbrandl** [comment]
@hho the size increase is due to the change in dependeny resolution. kscript does not rely on maven but is using aether instead.

**Comment by holgerbrandl** [comment]
Fixed and released to sdkman as v2.7.1. Tested in docker container and seems fine now.

Sorry for inconvenience.

**Comment by dharrigan** [comment]
Thank you! :-)

**Comment by marc0der** [comment]
I'm on holidays atm but I'll remove 2.7.0 from sdkman when I get to a computer. Alternatively, someone can simply raise a PR on our DB migrations repo.
