### ISSUE TITLE
Unable to install from Homebrew

### ISSUE THREAD

**Issue by lordcodes** [holgerbrandl/kscript#215]
When trying to install kscript from Homebrew, an error is printed about self-signed certificates. Not sure if this is related to fact that on the [homebrew-tap repo](https://github.com/holgerbrandl/homebrew-tap) some of the releases aren't linked to your GitHub user. 

```bash
brew install holgerbrandl/tap/kscript
==> Tapping holgerbrandl/tap
Cloning into '/usr/local/Homebrew/Library/Taps/holgerbrandl/homebrew-tap'...
fatal: unable to access 'https://github.com/holgerbrandl/homebrew-tap/': SSL certificate problem: self signed certificate
Error: Failure while executing; `git clone https://github.com/holgerbrandl/homebrew-tap /usr/local/Homebrew/Library/Taps/holgerbrandl/homebrew-tap --depth=1` exited with 128.
```

**Comment by holgerbrandl** [comment]
Not sure either about the problem. But I'll do a re-release using my github user. I'll need your help to test it, since I don't have access to a mac at the moment.

**Comment by lordcodes** [comment]
Okay thank you. Definitely, will try and install once I see it!

**Comment by holgerbrandl** [comment]
Done, please have a look

**Comment by lordcodes** [comment]
Thank you, all working for me now, not sure if it was environmental or if this fixed it, but all I can say is it is working!
