### ISSUE TITLE
How to use a kotlin multiplatform module as a dependency?

### ISSUE THREAD

**Issue by Danilo-Araujo-Silva** [holgerbrandl/kscript#221]
Hi,

I was checking this section: https://github.com/holgerbrandl/kscript#annotation-driven-script-configuration

Can we use a common module of a kotlin multiplatform project as a dependency?

For example, if I'm developing a cli/terminal application I could do something like this on my `build.gradle.kts`:

```
kotlin {
	...

	sourceSets {
		val jvmMain by getting {
			dependencies {
				implementation(project(":common"))
			}
		}

		...
	}
}
```

How could we use `implementation(project(":common"))` in our `kscript` files?

I've seen that something like

> @file:DependsOn("de.mpicbg.scicomp:kutils:0.4")

is interesting and almost could help me, but I'm not really certain how I could configure my `kscript` file to achieve the same result, since I'll not be using a `build.gradle.kts` (or if I could, I don't know how).

**Comment by holgerbrandl** [comment]
I have not yet worked with multi-platform projects, so may misread the problem.

The idea of kscript is to ease script configuration and execution in a shell environment. I'm not sure how compatible this idea is with multiplatform. E.g. do you expect kscript to run in a browser.

On a more technical level, you could simply figure out which dependencies are needed, and add them directly with @file:DependsOn. I'm afraid that there is no direct support for `implementation` present in kscript nor planned at the moment.

**Comment by Danilo-Araujo-Silva** [comment]
Hum, I see.

Well, my motivation to that is that I'm building an open source project to deploy all use cases of kotlin in a single project (desktop, ios, android, backend, browser, wasm, etc). And one of the use cases is the script possibility, but I would like to show how can we use the definitions of the common module in the other modules (script, desktop, android, etc.)

So I think this could be very interesting to be in the roadmap too, since we are moving to use, luckily, one language to do all parts and share code between this parts.

**Comment by holgerbrandl** [comment]
Not sure how to proceed here, so I'm closing this ticket. Feel welcome to reopen it if needed.
