### ISSUE TITLE
Consider switching to Kotlin DSL for generated `--idea` flag

### ISSUE THREAD

**Issue by mikeholler** [holgerbrandl/kscript#222]
Command:

```
kscript --idea some-file.kts
```

Produces an IntelliJ project with a `build.gradle` in the root. Since we all love Kotlin, it may make sense to transition this to a `build.gradle.kts` now that's got first party support in Gradle.

Thanks for such a great project!

**Comment by holgerbrandl** [comment]
Sounds like a great idea for a PR to me. Would you be willing to contribute it?

**Comment by holgerbrandl** [comment]
Any news, or shall we close this issue?

**Comment by mikeholler** [comment]
Hey @holgerbrandl, I don't personally have the time to contribute this change, and only wanted to suggest it here in case someone else wanted to take it up. In projects I manage, I generally leave tickets open if we still think it's a good idea so that others can come along and find something they may want to contribute. If you'd like to close it instead though, that's completely up to you.

Thanks for responding :smile:

**Comment by martinbonnin** [comment]
Fixed with https://github.com/holgerbrandl/kscript/pull/258
