### ISSUE TITLE
Use local gradle wrapper when creating package

### ISSUE THREAD

**Issue by elihart** [holgerbrandl/kscript#223]
When creating a package with `kscript --package some_script.kts` would it be possible to have kscript use the local gradle wrapper `./gradlew` instead of requiring `gradle` to be in the path?

For our scripts I am trying to work around the classpath loading bugs (https://github.com/holgerbrandl/kscript/issues/109) by packaging the scripts before execution, and our project uses the gradlew wrapper. It would be much nicer to have all our team's dev environments reuse the gradle wrapper instead of requiring everyone to setup `gradle` as well (particularly on CI where I would like to package and execute the script, instead of checking the binary into version control).

**Comment by holgerbrandl** [comment]
Indeed relying on a project specific version of gradle is better. However, how would you envision `kscript` to pick up where this `gradlew`` is located? I can't imagine a clean fix at the moment: Simply using a `gradlew` because it happens to sit in the working directory of the kscript process, seems too arbitrary to me to make it a proper fix.

**Comment by elihart** [comment]
For our cases checking if `gradlew` exists in the working directory and using it would be fine, but I understand your concerns about that being arbitrary. 

Possibly instead an argument could be passed to indicate that `gradlew` should be used?

**Comment by holgerbrandl** [comment]
Couldn't you _just_ patch your PATH before calling it? Like in 
```
ln -s ./gradlew /some/where/gradle; export PATH=/some/where:$PATH; kscript --package foo.kts
```
If not, could you provide a PR that would optionally use a custom gradle if defined via an environment variable called `KSCRIPT_GRADLE`?  Similar to https://github.com/holgerbrandl/kscript/blob/e841480b46a0356eadaa6cda2b5b05d2624f9b6b/src/main/kotlin/kscript/app/Kscript.kt#L26

**Comment by elihart** [comment]
yes, updating the PATH would work, especially for local machines. However, for CI machines I'm cautious of modifying the PATH to avoid any unintended side effects with the machine in later jobs.

I'd be happy to put up a PR with your suggestion, thanks!

**Comment by elihart** [comment]
I've opted instead to just add `./gradlew` to the PATH,  which seems to be working well.

Here is a script I am using to make it easy to do this for any script

`packageAndRunKts.sh`

```
#!/bin/bash

# This takes a kts file as a parameter, packages it with KScript, and then runs it.
# This is useful, because some script usages (like Kotlin compiler AST) only work if packaged first - https://github.com/holgerbrandl/kscript/issues/109.
# Packaging with Kscript also requires gradle on the PATH, which this takes care of using our local ./gradlew

fileName=$1

if [ -z "$fileName" ]; then
    echo "Kts file path must be provided as first argument"
    exit 1
fi

# Gradle is needed on the PATH by Kscript in order to package scripts.
# If gradle is not present in the path then we add the local gradlew to PATH so Kscript can use it
if ! [ -x "$(command -v gradle)" ]; then
    mkdir -p ~/usr/local/gradlew
    cwd=$(pwd)
   ln -sf "$cwd/gradlew" ~/usr/local/gradlew/gradle; export PATH=$PATH:~/usr/local/gradlew
   echo $PATH
fi

# This removes the path and prefix, leaving just the file name - ie 'foo/bar.kts' -> 'bar'
scriptName=$(basename "$fileName" .kts)

kscript --package "$fileName" && "./$scriptName"
```

**Comment by holgerbrandl** [comment]
Thanks for sharing @elihart
