### ISSUE TITLE
Python implementation of kscript

### ISSUE THREAD

**Issue by hanslovsky** [holgerbrandl/kscript#232]
I would like to create a Python implementation of kscript for ease of use on Windows machines without cygwin or other solutions and easy distribution through [PyPI](https://pypi.org) and [conda](https://conda.io).

As far as I can tell, the relevant bash code for `kscript` lives in [`src/kscript`](https://github.com/holgerbrandl/kscript/blob/ba74b620699a8811fcde68d382be2c70b96d7c6e/src/kscript). I [searched this repo for `"env bash"`](https://github.com/holgerbrandl/kscript/search?utf8=%E2%9C%93&q=%22env+bash%22&type=) and a few more files showed up (on commit ba74b620699a8811fcde68d382be2c70b96d7c6e):
 - `misc/experimental/kscriptJarStub`
 - `misc/experimental/kscriptD`
 - `test/resources/custom_dsl/mydsl`
 - `misc/kshell_launcher/kshell_kts.sh`
 - `misc/docker_tests.sh`
 - `test/test_suite.sh`
 - `src/main/kotlin/kscript/app/AppHelpers.kt`

I assume that anything with `test` or `experimental` in it would not be relevant for a Python implementation (for now), leaving only [`kshell_kts.sh`](https://github.com/holgerbrandl/kscript/blob/10a9cef1bab8fbb1d3a5730c5984a61322c4144d/misc/kshell_launcher/kshell_kts.sh) and [`AppHelpers`](https://github.com/holgerbrandl/kscript/blob/d61007133624789c3e012bd154224b9796081842/src/main/kotlin/kscript/app/AppHelpers.kt).

Is [`AppHelpers.packageKscript`](https://github.com/holgerbrandl/kscript/blob/d61007133624789c3e012bd154224b9796081842/src/main/kotlin/kscript/app/AppHelpers.kt#L285) intended to be run on the client machine? If yes, the [use of bash](https://github.com/holgerbrandl/kscript/blob/d61007133624789c3e012bd154224b9796081842/src/main/kotlin/kscript/app/AppHelpers.kt#L349-L351) may be prohibitive for a Python implementation of kscript.

Other issues are:
 - Should a Python implementation live in a separate repository or within the kscript main repository?
 - Potential name clashes of the python `kscript` executable with the existing `kscript` bash script

Possibly related: #36

**Comment by holgerbrandl** [comment]
Indeed, you could ignore `experimental` and `misc`. You need to widen your search by also including `evalBash` because kscript is actually launching a few shell processes internally to compile code etc.

Feel welcome to reimplement it, but for windows compatibility, you just need a bash shell (like git-bash) and bash on the PATH. This works for me, and if it does not for you, I'd consider it a bug that we should address.

Yes, packaging is intended to run on the client machine. See https://github.com/holgerbrandl/kscript#deploy-scripts-as-standalone-binaries

kscript is a shell tool. I'm not sure how to remove its dependency on the shell without rewriting it. So a python version should deserve an own repo imho. And to prevent user confusion a different name for the executable would clearly help.

**Comment by hanslovsky** [comment]
> Feel welcome to reimplement it, but for windows compatibility, you just need a bash shell (like git-bash) and bash on the PATH. This works for me, and if it does not for you, I'd consider it a bug that we should address.

I am a Linux user and not too familiar with Windows, but I would still like to make code available for use on Windows. I will investigate if git-bash is a viable solution in practice. A little overhead on the client side for installation is preferable to a complete re-implementation in Python, especially as git-bash is [available on conda](https://anaconda.org/conda-forge/git-bash). I will look into it and report my decision

**Comment by holgerbrandl** [comment]
I think the best approach for better platform interop would be to refactor ìnteral `evalBash` away. Next, the shell launcher itself could be easily reimplemented in any scripting lang and we could potentially even bundle it with the current installation bundles.

Another approach for better platform compatibility would be to use the kotlin compiler api (see #205).

**Comment by holgerbrandl** [comment]
I'm closing this ticket because it does not seem an issue with `kscript` itself.
