### ISSUE TITLE
Args does not include an "$0" equivalent containing the filename of the executed script

### ISSUE THREAD

**Issue by cgruber** [holgerbrandl/kscript#237]
Bash scripts are able to know the file name (as invoked) of the script via `$0`, but args[0] is the first element of the args, not the "zeroth arg" idea from bash.

There should be a script-friendly way to get the present script name or path or File, for use in error/usage messages, etc.

**Comment by holgerbrandl** [comment]
There is an environment variable called `KSCRIPT_FILE` which contains the $0 equivalent. Would this be sufficient for your intended use-case?

**Comment by holgerbrandl** [comment]
Closed due to inactivity. Feel welcome to continue the discussion as needed.
