### ISSUE TITLE
Generate Default Idea Run Configuration

### ISSUE THREAD

**Issue by forrestbice** [holgerbrandl/kscript#243]
The `idea` option for creating a cached / temporary Intellij project is great but I'd be really convenient  if there was a default Run Configuration generated as well as this is something I frequently find myself re-adding by hand. It appears this request was made before here: https://github.com/holgerbrandl/kscript/issues/125 but ultimately closed in favor of: https://github.com/holgerbrandl/kscript/issues/148. I've got a working branch going so I wanted to re-open this for discussion and put up a PR.

**Comment by holgerbrandl** [comment]
Fixed by PR #244.

Great intermediate fix until we may have direct plugin support for kscriplets in IJ.
