### ISSUE TITLE
Checksum of source on the AUR is wrong

### ISSUE THREAD

**Issue by sindrenm** [holgerbrandl/kscript#250]
For some reason, the SHA256 checksum provided in the [PKGBUILD in the Arch User Repository (AUR)][1]. It is listed as `3d62b0db226566506a2531d765547595867230cd5d44dbedc65301cadfecdaaf` in the generated PKGBUILD. However, the correct checksum for [kscript-2.9.0-bin.zip here on GitHub][2] is `85bbed4e20d40613b06c0e11cc9358b36000afebeb613baf07e975448ea18f2c`.

Looking at the release script, I can't really figure out why this is, though, as it does seem to upload the same file as it zips, and this is also the file from which the checksum is calculated. Perhaps you have some ideas? :confused: 

[1]: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=kscript
[2]: https://github.com/holgerbrandl/kscript/releases/download/v2.9.0/kscript-2.9.0-bin.zip

**Comment by CLOVIS-AI** [comment]
Same problem here, cannot install

**Comment by holgerbrandl** [comment]
I've pushed out a new release including the fix. Please try again.

**Comment by sindrenm** [comment]
Sweet, thanks! Works for me now. :heart_eyes:

**Comment by hanslovsky** [comment]
Can confirm, just updated my kscript successfully.

**Comment by CLOVIS-AI** [comment]
Can confirm as well, thanks ^^
