### ISSUE TITLE
--idea does not work

### ISSUE THREAD

**Issue by sethchhim** [holgerbrandl/kscript#259]
If you use `snap` or `flatpak` for IntelliJ, the `Boostrap IDEA from a kscript` feature will not work.

Example: 
`kscript --idea CountRecords.kts`

`Generate shell scripts` is also broken.

Solution:
I installed IntelliJ from JetBrain's toolbox appimage and it now works perfectly.
https://www.jetbrains.com/toolbox-app/

Closing this issue, just posting for reference if it can save anyone else some time troubleshooting.

**Comment by holgerbrandl** [comment]
Thanks for sharing your insights.
