### ISSUE TITLE
Debugging does only for for .kts files and not for .kt files

### ISSUE THREAD

**Issue by rossbacher** [holgerbrandl/kscript#266]
When i create the `.kts` script

```
#!/usr/bin/env kscript
@file:KotlinOpts("-J-Xdebug -J-Xrunjdwp:transport=dt_socket,address=localhost:8000,server=y,suspend=y,quiet=y")

val test = "Debug test"
println(test)
```

Then run it via `kscript Debug.kts` and connect a remote debugger from the IJ instance that was started with `kscript --idea Debug.kts` it does stop in the break points I set in the `println(test)` e.g..

However when I write the script as a `.kt` file like this:

```
#!/usr/bin/env kscript
@file:KotlinOpts("-J-Xdebug -J-Xrunjdwp:transport=dt_socket,address=localhost:8000,server=y,suspend=y,quiet=y")

fun main(args: Array<String>) {
    val test = "Debug test"
    println(test)
}
```

and use the same setup (`kscript --idea Debug.kt`) to create the IJ project and use the same setup for remote debugging, I can connect to the jvm instance but a breakpoint on `println(test)` e.g. is not hit.

**Comment by holgerbrandl** [comment]
I may do it differently, but this seems to work for me. The IDE is stopping at the breakpoint:
![image](https://user-images.githubusercontent.com/200952/84090075-fc65da00-a9f0-11ea-847c-33a6d4c317ba.png)

**Comment by rossbacher** [comment]
Ok, I spent some more time on this and figured out what the issue is here. If I run the `.kt` version from inside the virtual project (where the linked source files are ) it also stops at the breakpoints. (The `.kts` file does it in both instances (either ran from original location or from within the idea project).

The problem is that with more complex projects I cannot run them from inside the virtual project as it puts all dependencies into the same path and thus `@file:Include("somedir/somefile.kt")` that reside in sub directories don't work anymore.

**Comment by rossbacher** [comment]
I put up https://github.com/holgerbrandl/kscript/pull/268 to fix the issue. At least I can debug in our complex scripts now. Don't know if that would have any other implications but I don't think so.
