### ISSUE TITLE
Pre-compilation for "Included files"

### ISSUE THREAD

**Issue by serpro69** [holgerbrandl/kscript#272]
Is it possible to pre-compile included files (i.e. `@file:Include("common.kts")`) to have completion in the IDE?

**Comment by holgerbrandl** [comment]
Why would you need to do so? When creating a dev environment with --idea it should add @file:includes to the project and the ide should provide auto completion. If not, please add an example. Thx

**Comment by serpro69** [comment]
You're right, this works for `.kt` files, but not for `.kts` 
I suppose that's on IDEA's side though and not on kscript's.

**Comment by holgerbrandl** [comment]
It's not a flaw in the IDE but because of how the language is designed. kts can not be -- by language definition --- contain references that are used outside of the scope of that same kts file I think.
