### ISSUE TITLE
Using named parameters in `MavenRepository` annotation breaks actual values

### ISSUE THREAD

**Issue by serpro69** [holgerbrandl/kscript#274]
I'm trying to use `--package` option to create an executable file. In the script I'm using `@file:MavenRepository("id", "some-repo-url")` annotation to get the artifacts. It seems though, that this repo is not used when packaging the application and only jcenter is used:

```
[kscript] Resolving dependencies...
[kscript]     Resolving junit:junit:4.13...Done
[kscript]     Resolving info.picocli:picocli:4.4.0...Done
[kscript]     Resolving {custom-artifact}...
[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load '{custom-artifact} (runtime)' from ["jcenter (https://jcenter.bintray.com/, releases+snapshots) without authentication"] into /home/{user}/.m2/repository
```

**Comment by serpro69** [comment]
So the root cause is using named arguments in the annotation.
This works: `@file:MavenRepository("id", "url")`. 
This doesn't: `@file:MavenRepository(id = "id", url = "url").

Named parameters are also generating wrong custom maven repo values with `--idea` options:
```
repositories {
    maven {
        url 'url = "https://something-something"'
    }
}
```

**Comment by holgerbrandl** [comment]
Same here. I've added a test to prevent regressions. I'll try to fix it for the next release. If you like, you could also have a look into kscript.app.ScriptKt#collectRepos yourself where the parsing of the annotation options is implemented.
