### ISSUE TITLE
Docker image: kotlin command not found

### ISSUE THREAD

**Issue by JamiesWhiteShirt** [holgerbrandl/kscript#277]
Attempting to run kscript in Docker always results in the following error:
```
$ docker run -i holgerbrandl/kscript - < main.kts
/root/.sdkman/candidates/kscript/current/bin/kscript: line 36: kotlin: command not found
```

The `serandel/kscript` Docker image seems to work without this issue.

**Comment by holgerbrandl** [comment]
Shame on me for forgetting beloved kotlin itself when building the container :'-)

I've updated the `latest` image and . To try again you will need to delete your local image `holgerbrandl/kscript` first I think. See https://stackoverflow.com/questions/40084044/how-to-remove-docker-images-based-on-name
