### ISSUE TITLE
Making an executable without a build.gradle file

### ISSUE THREAD

**Issue by serpro69** [holgerbrandl/kscript#278]
Would be nice if the required build.gradle was generated if it's absent.
For example if I have a project with only one .kts script, adding a build.gradle seems excessive. Maybe some functionality of `--idea` option could be reused to generate a temporary build.gradle file?

**Comment by holgerbrandl** [comment]
You could create a build file by creating a temporary project with --idea . See  https://github.com/holgerbrandl/kscript#boostrap-idea-from-a-kscriptlet

**Comment by serpro69** [comment]
That's true, but that requires you to package the binary from the temporary project dir also, right? That seems to me like "workarounds", which I prefer to avoid :) 
Besides, I want to package the binary in the CI pipeline, and then publish it. Using `--idea` option in this case might not be possible at all in most cases.

**Comment by holgerbrandl** [comment]
Just to be on the safe side to make sure that a feature did not slip through unnoticed: Have you read the section about https://github.com/holgerbrandl/kscript#deploy-scripts-as-standalone-binaries

**Comment by serpro69** [comment]
I'm most definitely sure I did :) 
And I'm getting an error (which is why I raised this issue in the first place):
```
✓ kscript --package script.kts
[kscript] [ERROR] gradle is required to package kscripts
```
Though now that I read it more carefully I think it means "gradle distribution", not "gradle build file" :D Not sure why I made that assumption in the first place.

**Comment by holgerbrandl** [comment]
Indeed, the build.gradle is auto-generated by kscript. But until now, we do not install gradle (which imho would be bad practise), but assume the user has installed this already. You can do so easily, e.g. with sdk with

```
sdk install gradle
```

Maybe the error could be more descriptive here.
