### ISSUE TITLE
Kscript: script compilation failed

### ISSUE THREAD

**Issue by gmgulla** [holgerbrandl/kscript#288]
I can't execute a simple Kotlin script because of compilation failed due to an invalid argument. 

This is my Kotlin script:
```
#!/usr/bin/env kscript 
println("Helloooo")
```

Then I've writter my very simple script, I've add executable permission to execute it:
`chmod u+x SomeScript.kts`

This is the error:
```
$ ./SomeScript.kts
[kscript] [ERROR] compilation of './SomeScript.kts' failed
error: invalid argument: -d
info: use -help for more information
```
 
How can I fix it?

**Comment by holgerbrandl** [comment]
Not sure, your example works perfectly for me. Are you using v2.9.3 of kscript?  How did you install it? Could you type
```
which kscript
```
to ensure that the intended version is being used?

What are your versions of java and kotlin?

**Comment by gmgulla** [comment]
Solved! I had already properly installed kscript via Homebrew, but, for some reason, only `kotlinc` was out of the PATH. I added it, and now it works!

**Comment by holgerbrandl** [comment]
You're welcome.
