### ISSUE TITLE
.env support?

### ISSUE THREAD

**Issue by linux-china** [holgerbrandl/kscript#293]
Most tools support to load loads .env files, and make it easy to populate environment variables.

kscript could load .env file of current directory, and add them as env variables for kotlin scripts for  customized settings, such as database url, username, password etc.

Yes, we could load load settings from a properties file, but .env is almost standard way to load custom settings as env for CLI tools.

**Comment by holgerbrandl** [comment]
Couldn't you simply use https://github.com/cdimascio/dotenv-kotlin in your script? It's only one extra line to declare the dependency.
