### ISSUE TITLE
Using kscript as a library?

### ISSUE THREAD

**Issue by cfelde** [holgerbrandl/kscript#298]
Hey,

I was looking if kscript is available as a dependency/library. I found what looks like very old releases over at https://mvnrepository.com/artifact/com.github.holgerbrandl/kscript?repo=jcenter.

I'd like to avoid having a local kscript jar if possible.

**Comment by holgerbrandl** [comment]
No, it is not possible to use it as a library, If you need scripting library support, you could use the official kotlin scripting API. However, from what I know the docs are not that good yet. E.g. see https://discuss.kotlinlang.org/t/using-kotlin-script-experimental-api-how-to-retrieve-the-value-from-the-script/19788 for an example, or post your question in the kotlin slack scripting channel.
