### ISSUE TITLE
Self Update doesn't work with kscript v1.5.0

### ISSUE THREAD

**Issue by xgouchet** [holgerbrandl/kscript#30]
Running `kscript --help` on my machine gives this : 

> kscript - Enhanced scripting support for Kotlin on *nix-based systems.
> 
> Usage     : kscript <scriptfile, script-url, - for stdin, some kotlin code> [<script_args>]*
> Usage     : kscript --clear-cache     # wipe cached script jars and urls
> Usage     : kscript -i                # interactive shell with DEPS as declared in script
> 
> Copyright : 2017 Holger Brandl
> License   : MIT
> Version   : v1.5.0
> Website   : https://github.com/holgerbrandl/kscript

But when I try to run `kscript --self-update` (as described in the Readme) I get the following error : 

> /home/user/.kscript/scriptarg_cache_ad5dd5b728885618.kts:1:3: error: unresolved reference: self
> --self-update
>   ^
> /home/user/.kscript/scriptarg_cache_ad5dd5b728885618.kts:1:3: error: variable expected
> --self-update
>   ^
> /home/user/.kscript/scriptarg_cache_ad5dd5b728885618.kts:1:8: error: unresolved reference: update
> --self-update
>        ^
> ERROR: compilation of '/home/user/.kscript/scriptarg_cache_ad5dd5b728885618.kts' failed

**Comment by holgerbrandl** [comment]
Indeed, I've messed it up when preparing `kscript` for [skdman](http://sdkman.io/) in v1.5.0.  Sorry for inconvenience.

I've fixed the problem with v1.5.1, but for sure existing v1.5.0 installations need to be updated manually by running the installation bits from https://github.com/holgerbrandl/kscript#installation again.

**Comment by xgouchet** [comment]
Thanks a lot :)
