### ISSUE TITLE
MavenRepository environment variables are no longer resolved

### ISSUE THREAD

**Issue by Delorien84** [holgerbrandl/kscript#300]
In `@file:MavenRepository` the username and password are no longer resolved as environment variable. According to documentation username and password should be resolved as environmental variable string surrounded by double {} brackets. But it does not work:

```kotlin
@file:MavenRepository("internal", "https://artifactory/artifactory/libs-release", user="{{ARTIFACTORY_USERNAME}}", password="{{ARTIFACTORY_PASSWORD}}")
``` 

Commit 15ba17db46bc836c670177b4a12b3f1743a38a4a removed the functionality .

**Comment by holgerbrandl** [comment]
Indeed, it did. Sorry for the inconvenience.
