### ISSUE TITLE
Including scripts by relative reference

### ISSUE THREAD

**Issue by aartiPl** [holgerbrandl/kscript#303]
I have seen issue #218 and from that ticket, it looks like the problem is already solved, but in my opinion, it's not, or at least not in all cases.

Please consider the following directory structure:
![obraz](https://user-images.githubusercontent.com/1508798/106806709-922d3400-6668-11eb-8317-693de648f3be.png)

**service-script-a.kts** includes **common-script-a.kts**. But **common-script-a.kts** includes internally **common-script-b.kts**.
Now when I execute **service-script-a.kts** I get error: 

`[kscript] [ERROR] Failed to resolve //INCLUDE 'common-script-b.kts'
[[kscript] [ERROR] /home/vagrant/workspace/Kod/GitRepos/TestCase/service-a/common-script-b.kts (No such file or directory)]`

Fixing it shouldn't be difficult - it is enough to include files **always** relatively to the file which does the include. Without that, it is not possible to correctly structure scripts and encapsulate pieces of code.

I am attaching the above very simple test-case as a zip file.

[TestCase.zip](https://github.com/holgerbrandl/kscript/files/5921348/TestCase.zip)

**Comment by holgerbrandl** [comment]
Indeed this should work. Feel welcome to provide a PR. I could/will also have look, but I'm pretty much booked out at the moment.
