### ISSUE TITLE
Packaging a kts file on OpenJDK 11 causes a CAPSULE Version Parse Exception

### ISSUE THREAD

**Issue by Dantaro** [holgerbrandl/kscript#304]
Currently, using `kscript --package` while running Java 11 (Possibly 9+) causes a exception in Capsule when running the packaged version.

`CAPSULE EXCEPTION: Could not parse version: 11.0.9.1 while processing attribute Min-Update-Version: {}`

I'm not sure if this is an issue fixable in KScript

A minor work around for the moment is to run against Java 8, but that becomes less and less viable as time goes on.

**Comment by aartiPl** [comment]
There is a replacement of the capsule plugin in branch kscript_4.1. I am closing this ticket.
