### ISSUE TITLE
NoClassDefFound: java.sql

### ISSUE THREAD

**Issue by MagnusMG** [holgerbrandl/kscript#305]
Suddenly my kscripts stopped working. I always include a library that makes use of a few databases, and whenever I try to do anything database related I get` java.lang.NoClassDefFoundError` for some class in java.sql. It is like it cannot find the driver libraries (Oracle JDBC and Derby). Everything works fine in normal kotlin projects. It is just my kscripts that do not work. And they worked a few hours ago. 

Any ideas?

**Comment by holgerbrandl** [comment]
Sorry for the inconvenience. Maybe the used java changed? To analyze what's being used, you could run `kscript --help`. I've also noticed that because of the coming jcenter shutdown some library vendors moved their artefacts which breaks dependency chains.

**Comment by MagnusMG** [comment]
Eh, I seem to have been using the wrong jdk. (14 instead of 8). Embarrassing. That should have been the first thing I checked. 

Well, the resulting error message is a bit confusing, so perhaps somebody else can be helped by seeing this.

**Comment by holgerbrandl** [comment]
Very well then. I hope that you agree that this ticket can be marked as resolved then. Feel free to reopen if needed.
