### ISSUE TITLE
com.github.holgerbrandl:kscript-annotations:1.4 should move off JCenter before 2021.05.01

### ISSUE THREAD

**Issue by mz0** [holgerbrandl/kscript#306]
Cause JCenter goes down on that day
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by holgerbrandl** [comment]
Yeah I'm well aware of that. I will move it, I guess we can even preserve the coordinates.

**Comment by holgerbrandl** [comment]
Fixed, see  https://search.maven.org/artifact/com.github.holgerbrandl/kscript-annotations/1.4 Luckily the group-id could remain the same, so there should be little friction in the transition.

I've also removed jcenter as default repo when resolving dependencies. This change will be released in v3.1. So from now it is just maven-central.
