### ISSUE TITLE
@file:KotlinOpts("--module-path") @file:KotlinOpts("--add-modules java.sql") doesn't seem to work w/ JDK11

### ISSUE THREAD

**Issue by kenyee** [holgerbrandl/kscript#307]
Trying to use this because when I run w/ JDK11, GSon can't find java.sql.Time.

I get this error:
 error: unsupported argument: --add-modules

Is there any way to add this module if >JDK8 is detected?

**Comment by holgerbrandl** [comment]
I think to pass an argument directly the JVM you need to prefix it with -J. See `kotlin -help`

**Comment by holgerbrandl** [comment]
Duplicate of https://github.com/holgerbrandl/kscript/issues/163
