### ISSUE TITLE
Unable to use Dependencies

### ISSUE THREAD

**Issue by Bwvolleyball** [holgerbrandl/kscript#308]
KScript is failing to resolve dependencies on Maven Central.  This was working, now it's not.

Script configuration:

```kotlin
@file:MavenRepository("mavenCentral", "https://repo.maven.apache.org/maven2")

@file:DependsOn("org.yaml:snakeyaml:1.28")
```

-- I've added the firm declaration to mavenCentral in an attempt to force it to use this as a repository, we have other repos configured in our `~/.m2/settings.xml` and `~/.gradle/init.gradle.kts`, but I do not intend to ever use private repositories with kscript, I only want to use public libraries, such as this YAML parser.

Error I get when running this script:

```bash
./script.kts
[kscript] Resolving dependencies...
[kscript] Resolving org.yaml:snakeyaml:1.28...
[kscript] Resolving com.github.holgerbrandl:kscript-annotations:1.4...
[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
[kscript] [ERROR] Exception: java.lang.RuntimeException: File 'org.yaml:snakeyaml:1.28' not found
org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for org.yaml:snakeyaml:jar:1.28
org.eclipse.aether.resolution.DependencyResolutionException: Failed to read artifact descriptor for org.yaml:snakeyaml:jar:1.28
```

Alternatively, is there a way to enable more error output? I'm capable of debugging things if it's something with my gradle / maven configuration on my machine, but, this doesn't even tell me where it's looking to try to resolve this dependency.

Can confirm this dependency exists on Maven Central: https://search.maven.org/artifact/org.yaml/snakeyaml

kscript version:

```
Copyright : 2020 Holger Brandl
License   : MIT
Version   : v3.0.2
Website   : https://github.com/holgerbrandl/kscript
Kotlin    : 1.4.31-release-344
Java      : JRE 1.8.0_275
```

**Comment by Bwvolleyball** [comment]
I finally figured out it's reading my `~/.m2/settings.xml`, but this doesn't correctly resolve (although, I can build traditional maven projects just fine) - maybe there's a way to disable this?

Is it a side-effect that this inherits maven config? Isn't Kscript trying to provide a whole ecosystem for these dependencies?

https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/DependencyUtil.kt#L98

**Comment by holgerbrandl** [comment]
Kscript is just using the platform dependency resolver (that ships with kotlin). Afaik private repos pw-protected repos are supported by the resolver.

If you think that there could be an issue with that you could submit a ticket to https://youtrack.jetbrains.com/issues/KT. Not sure how to prepare a reproducible example though, but maybe you could at least provide some abstraction of how you declare your repo in your settings.xml.  (@ligee?)

**Comment by ligee** [comment]
It will be nice to reproduce it in the kotlin environment before submitting an issue. The simplest way is to take examples repo and modify a test in this project - https://github.com/Kotlin/kotlin-script-examples/tree/master/jvm/basic/jvm-maven-deps 
For debugging and more advanced usages you'll need to get a kotlin repo and look at this code https://github.com/JetBrains/kotlin/blob/master/libraries/scripting/dependencies-maven/src/kotlin/script/experimental/dependencies/maven/impl/aether.kt and tests around this module.

**Comment by Bwvolleyball** [comment]
Here's an example of the settings.xml we're using - these internal repos proxy any public ones.

I guess my confusion lies in the fact that this project allows for specifying additional / standalone repository configuration, but, is that even used if I have a `settings.xml`?  If this project is trying to provide repository configuration, then, shouldn't it entirely ignore my settings.xml anyways?

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.1.0 http://maven.apache.org/xsd/settings-1.1.0.xsd"
          xmlns="http://maven.apache.org/SETTINGS/1.1.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <servers>
        <server>
            <username>username</username>
            <password>password</password>
            <id>internal-readonly</id>
        </server>
    </servers>
    <mirrors>
        <mirror>
            <mirrorOf>*,!internal-releases,!internal-stage,!internal-snapshots</mirrorOf>
            <url>https://internal.com/repository/internal-snapshots-group/</url>
            <name>internal-snapshots-group</name>
            <id>internal-readonly</id>
        </mirror>
    </mirrors>

    <profiles>
        <profile>
            <id>artifact-repo</id>
            <repositories>
                <repository>
                    <id>internal-release</id>
                    <url>https://internal.com/repository/internal-releases/</url>
                    <snapshots><enabled>false</enabled></snapshots>
                    <releases><enabled>true</enabled></releases>
                </repository>
                <repository>
                    <id>internal-stage</id>
                    <url>https://internal.com/repository/internal-stage/</url>
                    <snapshots><enabled>false</enabled></snapshots>
                    <releases><enabled>true</enabled></releases>
                </repository>
                <repository>
                    <id>internal-snapshot</id>
                    <url>https://internal.com/repository/internal-snapshots/</url>
                    <snapshots><enabled>true</enabled></snapshots>
                    <releases><enabled>false</enabled></releases>
                </repository>
            </repositories>
            <pluginRepositories>
                <pluginRepository>
                    <snapshots><enabled>false</enabled></snapshots>
                    <releases><enabled>true</enabled></releases>
                    <id>internal-release</id>
                    <name>plugins-release</name>
                    <url>https://internal.com/repository/internal-releases/</url>
                </pluginRepository>
                <pluginRepository>
                    <snapshots><enabled>false</enabled></snapshots>
                    <releases><enabled>true</enabled></releases>
                    <id>internal-stage</id>
                    <name>plugins-stage</name>
                    <url>https://internal.com/repository/internal-stage/</url>
                </pluginRepository>
                <pluginRepository>
                    <snapshots><enabled>true</enabled></snapshots>
                    <releases><enabled>false</enabled></releases>
                    <id>internal-snapshot</id>
                    <name>plugins-snapshot</name>
                    <url>https://internal.com/repository/internal-snapshots/</url>
                </pluginRepository>
            </pluginRepositories>
        </profile>
    </profiles>

    <activeProfiles>
        <activeProfile>artifact-repo</activeProfile>
    </activeProfiles>
</settings>
```

**Comment by holgerbrandl** [comment]
I've tried again, and it seems to work (without any additional settings.xml)
```
brandl@ubuntu:scratch$ kscript issue308.kts 
[kscript] Resolving dependencies...
[kscript] Resolving org.yaml:snakeyaml:1.28...
[kscript] Resolving com.github.holgerbrandl:kscript-annotations:1.4...
[kscript] Dependencies resolved

```

System settings
```
brandl@ubuntu:scratch$ kscript --version
...
Kotlin    : 1.4.31-release-344
Java      : JRE 11.0.10+9
```

**Comment by Bwvolleyball** [comment]
Marking this as closed - I no longer have access to the settings.xml that was causing this problem, so there's no need to pollute this repo with the issue, especially since you can't reproduce it. Thanks for looking into this!
