### ISSUE TITLE
Failed to load dependencies

### ISSUE THREAD

**Issue by umasstr** [holgerbrandl/kscript#310]
In agreement with similar issues, it seems that kscript is unable to resolve dependencies. 
I am trying to use a kscript posted by this repo's author here: https://www.biostars.org/p/64346/

Using the author's docker image, I tried to run this scriptlet:

`docker run -i holgerbrandl/kscript https://git.io/vbJ4B features.bed`

Output:

> [kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
> [kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'de.mpicbg.scicomp:kutils:jar:0.9.0 (runtime)' from ["jcenter (https://jcenter.bintray.com/, releases+snapshots) without authentication"] into /root/.m2/repository

I also tried running this locally:

`docker run -i holgerbrandl/kscript - < gtf2bed.kts Idua_features.bed`

Output:

> [kscript] Resolving dependencies...
> [kscript]     Resolving de.mpicbg.scicomp:kutils:0.9.0...[kscript] [ERROR] Failed while connecting to the server. Check the connection (http/https, port, proxy, credentials, etc.) of your maven dependency locators. If you suspect this is a bug, you can create an issue on https://github.com/holgerbrandl/kscript
> [kscript] [ERROR] Exception: org.sonatype.aether.resolution.DependencyResolutionException: failed to load 'de.mpicbg.scicomp:kutils:jar:0.9.0 (runtime)' from ["jcenter (https://jcenter.bintray.com/, releases+snapshots) without authentication"] into /root/.m2/repository

**Comment by holgerbrandl** [comment]
Closed because of inactivity. Feel welcome to reopen if needed.
