### ISSUE TITLE
How to use Kotlin Native with kscript?

### ISSUE THREAD

**Issue by NightMachinary** [holgerbrandl/kscript#311]
It seems Kotlin Native is now somewhat production ready? Is it possible to use it with kscript?

**Comment by holgerbrandl** [comment]
The engine itself seems ready, but does it support all require APIs in particular File and URL? Also are all used dependencies of kscript _native-ready_? If so, we should certainly give it a try.

**Comment by NightMachinary** [comment]
@holgerbrandl Unfortunately, native kotlin requires the full Xcode for macOS. I guess we should wait some years more, though perhaps it can work on Linux.

Feel free to close this issue.

**Comment by holgerbrandl** [comment]
I don't even have a mac at the moment but I'm happy to accept donations to push this ticket forward. :-)
