### ISSUE TITLE
Please update AUR

### ISSUE THREAD

**Issue by neworld** [holgerbrandl/kscript#312]
Could you update AUR package: https://aur.archlinux.org/packages/kscript/. It is flagged outdated for a while. I assume https://github.com/holgerbrandl/kscript/blob/master/misc/kscript_release.sh was not used because the docker image is [also outdated](https://hub.docker.com/r/holgerbrandl/kscript/tags?page=1&ordering=last_updated). In regards to AUR, I could help maintain the package (username: `neworldlt`)

**Comment by holgerbrandl** [comment]
Any help is appreciated regarding AUR. I always struggled with the signing/auth process.

**Comment by neworld** [comment]
`aur` works via ssh using provided public key. You could change in `My account` after login here: https://aur.archlinux.org/

**Comment by holgerbrandl** [comment]
Fixed, see https://aur.archlinux.org/packages/kscript/

Thanks for the pointer and your patience.

**Comment by neworld** [comment]
Thanks! Now I can update kscript and jdk for all machines.
