### ISSUE TITLE
kscript --idea generated project, can't run debug

### ISSUE THREAD

**Issue by flashflexpro** [holgerbrandl/kscript#316]
StsAssumeAdmin.kts:
```

#!/usr/bin/env kscript

@file:JvmName("SomethingUnertique1234")
@file:CompilerOpts("-jvm-target 11")
@file:DependsOn("com.github.holgerbrandl:kscript-annotations:1.4")

@file:DependsOn("com.github.holgerbrandl:kutils:0.12")
@file:DependsOn("org.slf4j:slf4j-simple:1.7.25")
@file:DependsOn("software.amazon.awssdk:sts:2.16.34")



import software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider
import software.amazon.awssdk.regions.Region
import software.amazon.awssdk.services.sts.StsClient
import java.nio.file.Files
import java.nio.file.Path
import java.nio.file.StandardOpenOption
import java.util.function.Consumer



val credentials = StsClient.builder()
    .region(Region.US_EAST_1)
    .credentialsProvider(ProfileCredentialsProvider.create("aabb"))
    .build()
    .assumeRole(Consumer { b ->
        b.roleArn("arn:aws:iam::1234567:role/admin").roleSessionName("role-session---admin")
    }).credentials()

val adminCredsStr = """

[default]
aws_access_key_id = ${credentials.accessKeyId()}
aws_secret_access_key = ${credentials.secretAccessKey()}
aws_session_token = ${credentials.sessionToken()}

""".trimIndent()

val awsCredsPath = Path.of("/home/debian/.aws/credentials")

val credsTxt = Files.readString(awsCredsPath)
var filtered: String = credsTxt;

val idxDefa: Int = credsTxt.indexOf("\n[default]");
if (idxDefa > 0) {
    filtered = credsTxt.substring(0, idxDefa)
    val nexIdx = credsTxt.indexOf("\n[", idxDefa + 1);
    println( "nexIdx>>" + nexIdx )
    if (nexIdx > 0) {
        filtered = filtered + "\n" + credsTxt.substring(nexIdx)
    }
}


Files.writeString(awsCredsPath, filtered + "\n" + adminCredsStr)

```

try to run/debug the script in generated gradle project after imported successfully:

> /home/debian/openjdk-11.0.9_11/bin/java -javaagent:/home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111/lib/idea_rt.jar=45881:/home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111/bin -Dfile.encoding=UTF-8 -classpath /home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111.plugins/Kotlin/kotlinc/lib/kotlin-compiler.jar:/home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111.plugins/Kotlin/kotlinc/lib/kotlin-reflect.jar:/home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111.plugins/Kotlin/kotlinc/lib/kotlin-stdlib.jar:/home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111.plugins/Kotlin/kotlinc/lib/kotlin-script-runtime.jar org.jetbrains.kotlin.cli.jvm.K2JVMCompiler -kotlin-home /home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111.plugins/Kotlin/kotlinc -script /home/debian/IdeaProjects/mem-cdk/scripts/StsAssumeAdmin.kts
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by com.intellij.util.ReflectionUtil (file:/home/debian/.local/share/JetBrains/Toolbox/apps/IDEA-U/ch-0/211.6693.111.plugins/Kotlin/kotlinc/lib/kotlin-compiler.jar) to method java.util.ResourceBundle.setParent(java.util.ResourceBundle)
> WARNING: Please consider reporting this to the maintainers of com.intellij.util.ReflectionUtil
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> error: unresolved reference: CompilerOpts (StsAssumeAdmin.kts:4:7)
> error: unresolved reference: DependsOn (StsAssumeAdmin.kts:5:7)
> error: unresolved reference: DependsOn (StsAssumeAdmin.kts:7:7)
> error: unresolved reference: DependsOn (StsAssumeAdmin.kts:8:7)
> error: unresolved reference: DependsOn (StsAssumeAdmin.kts:9:7)
> error: unresolved reference: software (StsAssumeAdmin.kts:13:8)
> error: unresolved reference: software (StsAssumeAdmin.kts:14:8)
> error: unresolved reference: software (StsAssumeAdmin.kts:15:8)
> error: unresolved reference: StsClient (StsAssumeAdmin.kts:23:19)
> error: unresolved reference: Region (StsAssumeAdmin.kts:24:13)
> error: unresolved reference: ProfileCredentialsProvider (StsAssumeAdmin.kts:25:26)
> error: cannot infer a type for this parameter. Please specify it explicitly. (StsAssumeAdmin.kts:27:28)
> error: calls to static methods in Java interfaces are prohibited in JVM target 1.6. Recompile with '-jvm-target 1.8' (StsAssumeAdmin.kts:40:25)
> StsAssumeAdmin.kts:4:7: error: unresolved reference: CompilerOpts
> @file:CompilerOpts("-jvm-target 11")
>       ^
> StsAssumeAdmin.kts:5:7: error: unresolved reference: DependsOn
> @file:DependsOn("com.github.holgerbrandl:kscript-annotations:1.4")
>       ^
> StsAssumeAdmin.kts:7:7: error: unresolved reference: DependsOn
> @file:DependsOn("com.github.holgerbrandl:kutils:0.12")
>       ^
> StsAssumeAdmin.kts:8:7: error: unresolved reference: DependsOn
> @file:DependsOn("org.slf4j:slf4j-simple:1.7.25")
>       ^
> StsAssumeAdmin.kts:9:7: error: unresolved reference: DependsOn
> @file:DependsOn("software.amazon.awssdk:sts:2.16.34")
>       ^
> StsAssumeAdmin.kts:13:8: error: unresolved reference: software
> import software.amazon.awssdk.auth.credentials.ProfileCredentialsProvider
>        ^
> StsAssumeAdmin.kts:14:8: error: unresolved reference: software
> import software.amazon.awssdk.regions.Region
>        ^
> StsAssumeAdmin.kts:15:8: error: unresolved reference: software
> import software.amazon.awssdk.services.sts.StsClient
>        ^
> StsAssumeAdmin.kts:23:19: error: unresolved reference: StsClient
> val credentials = StsClient.builder()
>                   ^
> StsAssumeAdmin.kts:24:13: error: unresolved reference: Region
>     .region(Region.US_EAST_1)
>             ^
> StsAssumeAdmin.kts:25:26: error: unresolved reference: ProfileCredentialsProvider
>     .credentialsProvider(ProfileCredentialsProvider.create("mem-mon-dev"))
>                          ^
> StsAssumeAdmin.kts:27:28: error: cannot infer a type for this parameter. Please specify it explicitly.
>     .assumeRole(Consumer { b ->
>                            ^
> StsAssumeAdmin.kts:40:25: error: calls to static methods in Java interfaces are prohibited in JVM target 1.6. Recompile with '-jvm-target 1.8'
> val awsCredsPath = Path.of("/home/debian/.aws/credentials")
>                         ^
> 
> Process finished with exit code 1
> 

Any idea please?

**Comment by holgerbrandl** [comment]
I think you've discovered https://youtrack.jetbrains.com/issue/KTIJ-11058 Feel welcome to upvote it. As a workaround, you could simply resolve the symlink with an actual file.
