### ISSUE TITLE
Script with dash in filename doesn't work

### ISSUE THREAD

**Issue by kashano** [holgerbrandl/kscript#32]
I was playing around with spark to see if kscript + spark would be a nice replacement for a python + flask script I have, so I created a script file called `spark-server.kts` with the following contents:

```kotlin
#!/usr/bin/env kscript

//DEPS com.sparkjava:spark-kotlin:1.0.0-alpha

import spark.kotlin.*

val http: Http = ignite()

http.get("/hello") {
        "Hello Spark Kotlin!"
}
```

When I tried to run it with `./spark-server.kts` I got the following error:

`error: could not find or load main class Main_Spark-server`

Then I renamed it to `sparky.kts` and everything worked ok.

BTW, kscript is really cool!

**Comment by holgerbrandl** [comment]
Indeed, thanks for reporting it. You can run `kscript --self-update` to fetch the updated release v1.52. 

Feel welcome if you have further questions or suggestions.
