### ISSUE TITLE
Terminate script immediately with some exit code

### ISSUE THREAD

**Issue by prayutsu** [holgerbrandl/kscript#321]
Is there any way to finish the execution of a script abnormally and also detecting this?
I want that if a certain condition is not met, the script should finish its execution with failure.
I couldn't find any examples in the documentation. 
If there's a solution for this, then please do include this in the documentation.

**Comment by holgerbrandl** [comment]
What about `kscript 'System.exit(1)'; echo $?`? This reports 1 as intended. Feel welcome to PR to include this if needed.

**Comment by prayutsu** [comment]
Thanks, @holgerbrandl.
I think it was quite trivial, we may not need to include this. You can close this issue now.

**Comment by holgerbrandl** [comment]
Thanks for your input & feedback.
