### ISSUE TITLE
Bootstrap headers not working (bare centeos)

### ISSUE THREAD

**Issue by robert2411** [holgerbrandl/kscript#324]
When I run a simple script with the bootstrap headers I get the folloing error:
`./test.kts: line 6: exec: kscript: not found`

I created a reproducable in docker

```
FROM centos
RUN yum install unzip -y
RUN yum install zip -y
WORKDIR /project
COPY ./test.kts /project
RUN chmod +x test.kts
RUN ./test.kts
```

the script
```
#!/bin/bash

//usr/bin/env echo '
/**** BOOTSTRAP kscript ****\'>/dev/null
command -v kscript >/dev/null 2>&1 || curl -L "https://git.io/fpF1K" | bash 1>&2
exec kscript $0 "$@"
\*** IMPORTANT: Any code including imports and annotations must come after this line ***/


println("Hello from Kotlin!")
for (arg in args) {
    println("arg: $arg")
}
```

**Comment by holgerbrandl** [comment]
Hmm,  I can't reproduce the problem yet. I've uninstalled kscript and ran your script, which works fine: It installs kscript via sdkman and runs the script afterwards.

The install procedure is pulled from https://raw.githubusercontent.com/holgerbrandl/kscript/master/misc/boostrap_header.sh so maybe this fails in your environment?

**Comment by holgerbrandl** [comment]
It seems that the bootstrap header is not correct. 

Currently with
```
#!/bin/bash

//usr/bin/env echo '
/**** BOOTSTRAP kscript ****\'>/dev/null
command -v kscript >/dev/null 2>&1 || curl -L "https://git.io/fpF1K" | bash 1>&2
exec kscript $0 "$@"
\*** IMPORTANT: Any code including imports and annotations must come after this line ***/
```
it can't find kscript because it has not sourced the init-script from SDK. I think `source "$SDKMAN_DIR/bin/sdkman-init.sh"` is missing in before exec. What do you think?

**Comment by wuseal** [comment]
I saw the log that I pasted, It has sourced the sdk script:
```
Setting kscript 3.1.0 as default.
$ source /Users/user/.sdkman/bin/sdkman-init.sh
./test.kts: line 6: exec: kscript: not found
```
But also error with can't find `kscript`

**Comment by wuseal** [comment]
I fixed it by change the bootstrap header to next:
```
//usr/bin/env echo '
/**** BOOTSTRAP kscript ****\'>/dev/null
command -v kscript >/dev/null 2>&1 || curl -sL "https://git.io/fpF1K" | bash 1>&2
source "$HOME/.sdkman/bin/sdkman-init.sh"
exec kscript $0 "$@"
\*** IMPORTANT: Any code including imports and annotations must come after this line ***/

```

**Comment by wuseal** [comment]
If I execute the `test.kts` by this way:
```. ./test.kts```
It seems also work without modify the bootstrap header

Ref: https://stackoverflow.com/questions/16011245/source-files-in-a-bash-script

**Comment by holgerbrandl** [comment]
However, it is still broken, as most users won't use/know this workaround. My bash skills are unfortunately also limited.
We somehow need to backport the workaround into the preamble.

**Comment by wuseal** [comment]
I advice change the bootstrapheader to next:
```
//usr/bin/env echo '
/**** BOOTSTRAP kscript ****\'>/dev/null
command -v kscript >/dev/null 2>&1 || source /dev/stdin <<< "$(curl -L https://git.io/fpF1K)"
exec kscript $0 "$@"
\*** IMPORTANT: Any code including imports and annotations must come after this line ***/
```
I'v test it, It works fine. How do you think @holgerbrandl

**Comment by holgerbrandl** [comment]
Thanks for the fix.
