### ISSUE TITLE
Updates to examples

### ISSUE THREAD

**Issue by speedenator** [holgerbrandl/kscript#33]
Thanks for putting this up... I've been playing with it to do quick kotlin prototyping.

Spent the morning getting it working, ended up being two small bugs:
1) using the github URL for resolving dependencies didn't seem to work on OSX; kept getting error: could not find or load main class Main_Scriptarg_cache_3335d424be6c36f7 when using anything with //DEPS. Putting resdeps.kts in my ~/bin solved the problem.

2) bug: in the example for Docopt, there's a line of doArgs.joinToString(). Should just be doArgs.

Fun stuff regardless, thanks!

**Comment by holgerbrandl** [comment]
Concerning 1.
Sorry for inconvenience, but I can't reproduce it yet. I've tried the following on Macos sierra with kotlin 1.1.3-2 (JRE 1.8.0_131-b11):
```
[brandl]$ which kscript
/Users/brandl/.sdkman/candidates/kscript/current/bin/kscript
[brandl]$ kscript --version
kscript - Enhanced scripting support for Kotlin on *nix-based systems.

Usage     : kscript <scriptfile, script-url, - for stdin, some kotlin code> [<script_args>]*
Usage     : kscript --clear-cache     # wipe cached script jars and urls
Usage     : kscript -i                # interactive shell with DEPS as declared in script

Copyright : 2017 Holger Brandl
License   : MIT
Version   : v1.5.3
Website   : https://github.com/holgerbrandl/kscript
[brandl]$ which resdeps.kts
[brandl]$ kscript --clear-cache
Cleaning up cache...
[brandl]$ kscript https://git.io/v1cG6 my argu ments
Hello kscript-user
The arguments were my, argu, ments
```

So it seems that dependency resolutions works fine with kscript even for URLs. Could you provide more details/example how it failed for you?

Concerning 2. 
Indeed, I've fixed the docopt example. Actually I've also written a more convenient wrapper in https://github.com/holgerbrandl/kscript-support-api/blob/master/src/main/kotlin/kscript/util/DocOpt.kt. See https://gist.github.com/holgerbrandl/a712112c392400ad503a46bcefe706a6 for an example.

**Comment by holgerbrandl** [comment]
feel welcome to still comment. Just closed due to inactivity.
