### ISSUE TITLE
Gradle 7 support

### ISSUE THREAD

**Issue by c47harsis** [holgerbrandl/kscript#335]
It doesn't work with gradle 7.x due to this [gradle-capsule-plugin issue](https://github.com/danthegoodman/gradle-capsule-plugin/issues/43) 😢

**Comment by holgerbrandl** [comment]
Indeed, unfortunately, the plugin has been abandoned.

**Comment by seanabraham** [comment]
@holgerbrandl are there any plans or thoughts about moving off capsule for the usage of `kscript --package` seeing as the gradle plugin and underlying library both appear abandoned now?

**Comment by vsajip** [comment]
I find that `--package` doesn't work with Gradle 6.9.2 either:
```
$ gradle -version

------------------------------------------------------------
Gradle 6.9.2
------------------------------------------------------------

Build time:   2021-12-21 20:18:38 UTC
Revision:     5d94aa68c0fdbe443838bb977080e3b9f273e889

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          11.0.15 (Private Build 11.0.15+10-Ubuntu-0ubuntu0.20.04.1)
OS:           Linux 5.4.0-117-generic amd64

$ kscript --package listener.kts 
[kscript] Packaging script 'listener.kts' into standalone executable...
[kscript] [ERROR] Packaging for path: '/home/vinay/.kscript/cache/package_e63aab3c3d2baa77f348edbc61cce0b4' failed:Command     : bash -c cd '/home/vinay/.kscript/cache/package_e63aab3c3d2baa77f348edbc61cce0b4' && gradle simpleCapsule
[kscript] [ERROR] Exit Code   : 1   
[kscript] [ERROR] Stdout      : 
[kscript] [ERROR] Stderr      : 
[kscript] [ERROR] 
[kscript] [ERROR] FAILURE: Build failed with an exception.
[kscript] [ERROR] 
[kscript] [ERROR] * What went wrong:
[kscript] [ERROR] Could not determine the dependencies of task ':simpleCapsule'.
[kscript] [ERROR] > Resolving dependency configuration 'runtime' is not allowed as it is defined as 'canBeResolved=false'.
[kscript] [ERROR]   Instead, a resolvable ('canBeResolved=true') dependency configuration that extends 'runtime' should be resolved.
[kscript] [ERROR] 
[kscript] [ERROR] * Try:
[kscript] [ERROR] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
[kscript] [ERROR] 
[kscript] [ERROR] * Get more help at https://help.gradle.org
[kscript] [ERROR] 
[kscript] [ERROR] BUILD FAILED in 2s
[kscript] [ERROR] 
```
Can you please indicate a version of Gradle for which the `--package` functionality is known to work?

**Comment by aartiPl** [comment]
There is help needed with the packaging option. It is known to not work already for a longer time. In the new version of kscript (4.0.+) the functionality of the capsule plugin is encapsulated, so preparing a patch that will revive it shouldn't be difficult. PRs for fixing this functionality are warmly welcome :-)

**Comment by vsajip** [comment]
> In the new version of kscript (4.0.+) the functionality of the capsule plugin is encapsulated

Well, I'm using 4.0.3. Where is the functionality of the capsule plugin encapsulated? It still seems to generate `build.gradle.kts` referencing the Gradle plugin - if that is unmaintained, then what broad approach would be used to plug the gap? I'm not familiar with the code base, so could use some pointers as to where to look ...

**Comment by aartiPl** [comment]
Sure. Here is the main file which is responsible for creating Capsule. 
https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/creator/PackageCreator.kt

It needs to be decided what solution to use (if the original plugin is unmaintained then the old way of creating capsules may be no more feasible) and to implement code in the above file and supporting files (if needed):
https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/code/Templates.kt
https://github.com/holgerbrandl/kscript/blob/master/src/main/kotlin/kscript/app/code/GradleTemplates.kt

**Comment by vsajip** [comment]
Thanks @aartiPl for the pointers. I have a question: in this line

https://github.com/holgerbrandl/kscript/blob/dc827753adf707cf31cd220716e85139cae2d9cd/src/main/kotlin/kscript/app/creator/PackageCreator.kt#L28

The `appName` value should be whatever script is being packaged, shouldn't it? So `foo.kts` would lead to a script `build/libs/foo`.  Have I misunderstood something?

**Comment by vsajip** [comment]
#364 should fix this - please review and comment.

**Comment by aartiPl** [comment]
That was quick! :-) Please give me some time to review this as I am quite busy until the end of the next week. In the meantime, you can consider adding tests and generally making the solution bulletproof.

To start tests (only Linux for now) you have to go into the test directory and:
1. source setup_environment.sh (it's optional, but will help with debugging)
2. ./linux_suite.sh

You will have to uncomment packaging in linux_suite.sh and implement some tests in suite/packaging.sh

To run only packaging tests just run:
./linux_suite packaging

**Comment by vsajip** [comment]
> In the meantime, you can consider adding tests

Thanks for the pointers. I'll see what I can do, but I'm fairly busy next week with existing commitments. Are there no existing tests for packaging? I ran `gradle build` which claims to build everhthing and run the tests, and everything seems to have passed, but I didn't look in detail, just at the final result. Also I don't see a `linux_suite.sh`, only a `test_suite.sh` - is this on some other branch than `master`?

**Comment by vsajip** [comment]
The package creator code you pointed me to created the package in `~/.kscript/cache/package_<HASH>/build/libs` - I don't see any logic to copy the final executable somewhere else. However, the test suite seems to be expecting the created executable to be in the current directory - is that right? As I can't see how the previous version on `master` behaves, I'm not sure if the tests need to be changed or not. The first test is

```
assert "rm -f ${PROJECT_DIR}/test/package_example && kscript --package ${PROJECT_DIR}/test/resources/package_example.kts &>/dev/null && ${PROJECT_DIR}/test/package_example 1" "package_me_args_1_mem_5368709120"
```
However, I don't have 5GB of memory on my machine, so this test wouldn't work anyway.  The max memory  on my machine returned is 980MB. Perhaps change the JVM memory options in the test to 500MB?

**Comment by aartiPl** [comment]
This is for the old version of kscript packaging, which doesn't work anyway. So, in my opinion, you can safely change current tests and provide your own, which will be better suited for the current solution.

**Comment by vsajip** [comment]
See also #365

**Comment by aartiPl** [comment]
The patch is merged and kscript works with Gradle 7, so I think it is time to close this issue...
