### ISSUE TITLE
`jvm-target 17` isn't supported in compiler opts

### ISSUE THREAD

**Issue by eygraber** [holgerbrandl/kscript#338]
I get an error that says:

```
error: unknown JVM target version: 17
Supported versions: 1.6, 1.8, 9, 10, 11, 12, 13, 14, 15, 16
```

**Comment by holgerbrandl** [comment]
It passes these arguments just on to the kotlin executable using the -X flag. So you may want to check what version of kotlin is running in your shell, and if it supports 17 as target.

**Comment by eygraber** [comment]
I didn't realize that. Updating my local Kotlin to 1.6.0 fixes the issue! Thank you!
