### ISSUE TITLE
Kscript in VSC

### ISSUE THREAD

**Issue by MagnusMG** [holgerbrandl/kscript#339]
I have finally managed to get Visual Studio Code to agree with kscript scripts, and [I wrote down the tweaks necessary](https://magnusgunnarsson.se/offentlig/kscript-in-visual-studio-code-vsc/). I thought other people might be interested.

**Comment by holgerbrandl** [comment]
Thanks for the pointer. I've updated the readme accordingly in https://github.com/holgerbrandl/kscript/commit/c7bc1985

**Comment by dazraf** [comment]
Honestly, I think we can learn a lot from JBang - one line CLI invocation that downloads vscode if not available, configures it with the appropriate plugins, downloads the JDK (!) etc.
