### ISSUE TITLE
Include/Import local file dependency

### ISSUE THREAD

**Issue by xgouchet** [holgerbrandl/kscript#34]
In a project, I have multiple kotlin script files, and I have some methods I need to use in most, if not all script. 

Is there an existing way to write these method in a single external file, and include it from the other scripts ? 

eg : 
**utils.kts**

```kotlin
fun foo(s : String) : String {
  //...
}
```

**myscript.kts**

```kotlin
#!/usr/bin/env kscript

//INCLUDE utils.kts

foo(args[0])
```

**Comment by holgerbrandl** [comment]
Nice idea, and it seems easy to do.

But how do you write those scripts? Since the IDE won't resolve //INCLUDE you'll get tons of red code, don't you?

**Comment by holgerbrandl** [comment]
I've implemented it in a separate branch for now. See https://github.com/holgerbrandl/kscript/blob/include_directive/test/resources/includes/include_variations.kts for an example. Feel welcome to let me know what you think.

**Comment by xgouchet** [comment]
That seems perfect for what I want !

**Comment by holgerbrandl** [comment]
I'm still skeptical if it makes sense to include it into the release branch because of missing IDE support. All the included bits will light up in bright red in the master script. How would you code them efficiently without pain?

**Comment by Bwvolleyball** [comment]
Was anything ever decided as to how to add IDE support for `//INCLUDE` files?

**Comment by holgerbrandl** [comment]
In general, the feature has been added, see https://github.com/holgerbrandl/kscript#ease-prototyping-with-include.

Except for IDE support, which would require a separate plugin. However, its fairly easy to configure the IDE accordingly in my experience.
