### ISSUE TITLE
4.X Improvments

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/kscript#344]
Extracted from @aartiPl  4.x change-log

SUGGESTIONS:
* I would drop old annotations based on comments or at least depreciate them 
* It's worthy to consider dropping ability to reference script by $HOME and by '/'. It will break other scripts if used in web scripts.
* There might be duplicate names when loading even different files from URI. Then when the idea project creates source dir it will fail: e.g. idea project from include_variations.kts. Requires some other way of setting up IDEA project.
* Handling of "Repository" annotation in parser / resolver - it is Kotlin standard, while kscript is using MavenRepository
* Improve unit tests

**Comment by aartiPl** [comment]
I think we should close this ticket - its content is in the TODO file.
