### ISSUE TITLE
4.X Regression: Can't import DependsOn anymore

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/kscript#346]
@aartiPl In 3.X when it detected the presence of any kscript-annotation, it automatically added kscript-annotations dependency. Now  the new preprocessor seems to strip all annotations from the script and not add elements to the classpath internally. 

Was/is this intended?

For example see https://github.com/holgerbrandl/kscript/issues/345#issuecomment-1112429482 which now fails to compile.

**Comment by aartiPl** [comment]
I will check it - not sure right now.

**Comment by holgerbrandl** [comment]
I'd consider this a minor regression only. Typically the user should/would not import DependsOn or any other annotation directly. Not sure why the user from the example did so.

**Comment by aartiPl** [comment]
Were you able to downgrade dependencies? I can try to do it on my side...

**Comment by aartiPl** [comment]
Yes, indeed this functionality was accidentally lost in refactoring. But before re-adding it I would rethink the requirements.

Can you please help me understand the use case and requirements for importing kscript-annotations? As the parsing is done based on text representation it is not needed to execute a script. I can only understand adding it to an idea project, so IDE is not erroring on annotations (which BTW. doesn't happen for me anyway...).

I think also that if it needs to be readded I would do that regardless of the existence of kscript annotations in script code - I would just add library in every case. That way we will avoid unnecessary dependencies in the kscript code.

**Comment by holgerbrandl** [comment]
You're right it's a legacy behaviour which is functionally not relevant. Let's leave it away. It's a simpler design

Previously, kscript-annotations were needed to compile the script, because the annotations were not stripped away before compiling the script.
