### ISSUE TITLE
Os type check seems wrong

### ISSUE THREAD

**Issue by justixLoL** [holgerbrandl/kscript#356]
Hi Holger,

It seems that [comparison](https://github.com/holgerbrandl/kscript/blob/63b3f5ebe576c5885c3d23f87854f397a9263071/src/main/kotlin/kscript/app/model/OsType.kt#L12) of current os should be changed from `equals` to `contains`:

Cause on version 4.0.2 I get the error 
`[kscript] [ERROR] Unsupported OS: darwin21` because 'darwin' in your enum != 'darwin21'
On version 4.0.0 all is good

**Comment by holgerbrandl** [comment]
Sorry for inconvenience. Could you submit a PR to the 4.1 branch?

**Comment by justixLoL** [comment]
@holgerbrandl Sure

**Comment by justixLoL** [comment]
@holgerbrandl https://github.com/holgerbrandl/kscript/pull/357

**Comment by aartiPl** [comment]
I have backported it also to the master branch. In fact, I think that Mac is reporting OSTYPE incorrectly - it should contain only single information about the type of OS, not a specific version or any additional information.

Maybe we can wait a bit if something pops up, and if not - do another bugfix release.

**Comment by aartiPl** [comment]
Should be fixed in 4.0.3 - please reopen if the problem persists...
