### ISSUE TITLE
Cant use kscript from sdkman on macos 10.15 darwin19

### ISSUE THREAD

**Issue by jayvdb** [holgerbrandl/kscript#358]
While attempting to workaround https://github.com/holgerbrandl/kscript/issues/355 , I tried kscript from sdkman on macos 10.15.

It installs correctly without any warning, 

> Installing: kscript 4.0.2
> Done installing!
> Setting kscript 4.0.2 as default.

But when running it I encounter

> [kscript] [ERROR] Unsupported OS: darwin19

I dont see any documentation on sdkman.io about which versions of macos were supported.  Maybe 10.15 is too old.

Ah, it looks like this is fixed by https://github.com/holgerbrandl/kscript/commit/8dc55604013fccdd6f1e99330ff3b3bc3525b345 , and so should be fixed in the next release.

**Comment by jayvdb** [comment]
And there is an existing issue about this https://github.com/holgerbrandl/kscript/issues/356

**Comment by aartiPl** [comment]
Should be fixed in 4.0.3 - please reopen if the problem persists...
