### ISSUE TITLE
[kscript] [ERROR] Unsupported OS: darwin21

### ISSUE THREAD

**Issue by angelina-andronova-xapo** [holgerbrandl/kscript#359]
I am trying to run `kscript` on M1 Monterey and i get error `[kscript] [ERROR] Unsupported OS: darwin21`.

**System information**
 - OS version: macOS Monterey 12.3.1, Apple M1
 - Kotlin version: kotlinc-jvm 1.6.21 (JRE 11.0.14+8-LTS-263)
 - Maven version: Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)
 - KScript version:  [kscript] [ERROR] Unsupported OS: darwin21

**Comment by holgerbrandl** [comment]
I think this should be fixed in v4.0.3. Please reopen if not.
