### ISSUE TITLE
Why the need to pass $OSTYPE on the command line?

### ISSUE THREAD

**Issue by vsajip** [holgerbrandl/kscript#367]
Is it not possible to determine the OS the system is running on without this?

**Comment by aartiPl** [comment]
As far as I know, It is not possible to find out if the system is Cygwin or MSys, but for those systems, paths have to be converted to correctly start the bash process. Otherwise, we can detect the system type.

**Comment by vsajip** [comment]
The following script:
```kotlin
import java.io.BufferedReader
import java.io.IOException
import java.util.concurrent.TimeUnit

fun whatsMyOS(): String? {
    val cmd = "uname -o".split(" ")
    try {
        val proc = ProcessBuilder(*cmd.toTypedArray())
                .redirectOutput(ProcessBuilder.Redirect.PIPE)
                .redirectError(ProcessBuilder.Redirect.PIPE)
                .start()

        proc.waitFor(60, TimeUnit.MINUTES)
        val stdout = proc.inputStream.bufferedReader().readText()
        return stdout.replace("GNU/", "").toLowerCase()
    } catch(e: IOException) {
        e.printStackTrace()
        return null
    }
}

println(whatsMyOS())
```
Should print `linux`, `darwin`, `cygwin`, `msys` on the various POSIX systems. Also, why pass it as a command line argument when it could be picked up as an environment variable?

**Comment by aartiPl** [comment]
Unfortunately, it won't work for Windows as there is no 'uname' command. Also calling external processes is quite heavy and will consume additional time for kscript execution (which is not desired for scripting solution).

In regards to passing value by env variable: this OSTYPE env is somewhat special in that regard: it can not be read by normal Java way of reading env variables. Seems that it is specific to the bash environment and is not like the real env variable, so basically this method doesn't work.

What's wrong with passing OSTYPE as kscript argument? Do you see any issues with that?

**Comment by vsajip** [comment]
> Unfortunately, it won't work for Windows as there is no 'uname' command

But `uname` need only be invoked to distinguish between `cygwin` and `msys`, right? 

> What's wrong with passing OSTYPE as kscript argument? Do you see any issues with that?

Well, it clearly works, but it's just ugly, and AFAIK no other cross-platform scripting environment seems to need such an approach.

There's another thing: on Windows, a `.exe` is generally reckoned to be the best form of delivering an application or mini-application - better than `.bat`, `.cmd` or Bash script, since all have to support `.exe` files on Windows. Now in the Python world, there are executable zips just as Java has in `.jar`, and I maintain [a set of executable launchers for Windows](https://github.com/vsajip/simple_launcher) which you prepend to the jar along with a shebang to create a `.exe`.  When it's launched, the code extracts the shebang and calls the interpreter mentioned in it, along with any command line arguments in the shebang, and the end result is that the interpreter specified in the shebang "executes" the archive. However, it doesn't expect to pass an OSTYPE argument which is not intended to be seen by the user code in the script! And whereas the `kscript` project may or may not be interested in this approach, I already have projects where I deploy single-file executables which are launcher (on Windows) + shebang + shadowJar, and it seems to work well. I'm just exploring this approach with Kotlin scripts at the moment, though I have as yet no specific proposals to make.

**Comment by vsajip** [comment]
> this OSTYPE env is somewhat special in that regard: it can not be read by normal Java way of reading env variables. Seems that it is specific to the bash environment and is not like the real env variable, so basically this method doesn't work.

If you do `export OSTYPE=$OSTYPE` in a Bash script, the `OSTYPE` variable should then be available to Java (or any other program) as a normal environment variable.

**Comment by aartiPl** [comment]
Yes, I have considered the approach with exporting OSTYPE, but I think that approach that explicitly passes parameters is more clear and has the advantage of not "polluting" env variables space with additional variables. Also in regards to shebang line: you will provide there anyway "kscript" as interpreter, not the real line which executes kscript (kotlin -classpath "..." kscript.app.KscriptKt ....). So passing OSTYPE will be encapsulated inside kscript anyway.

**Comment by aartiPl** [comment]
Similar request:
https://github.com/holgerbrandl/kscript/issues/362

In this case, a wrapper should be developed to help call Kotlin scripts from Python.

**Comment by aartiPl** [comment]
Closing as per above comments.
