### ISSUE TITLE
Add kscript to Homebrew

### ISSUE THREAD

**Issue by henrik242** [holgerbrandl/kscript#50]
Homebrew is the most used package manager on macOS: https://brew.sh/

**Comment by yschimke** [comment]
A big +1 to this, it seems like people opted in to homebrew don't have much option e.g. mylibrary -> kscript -> kotlin.  I can help set this up, it's just a trivial github repo

e.g. https://github.com/yschimke/homebrew-tap

**Comment by henrik242** [comment]
A tap is good, even better to get it added upstream

**Comment by yschimke** [comment]
For now https://github.com/yschimke/homebrew-tap/blob/master/kscript.rb

$ brew install yschimke/tap/kscript

**Comment by holgerbrandl** [comment]
Thanks, this looks easier than I thought. We could add this kscript.rb to the release branch of the kscript repo. Would `brew` be clever enough to update kscript when the files has changed, so can we do something like `brew update --include-taps`?

**Comment by yschimke** [comment]
IIUC this work via

username/collection/project -> https://github.com/[username]/homebrew-[collection]/blob/master/[project].rb

So it's hard to have it in the same repo you use for development.  But you could certainly update the file on every release and then yes, brew will let people know updates are available.

**Comment by holgerbrandl** [comment]
I followed your suggestion. See https://github.com/holgerbrandl/kscript/blob/master/README.md#installation-with-homebrew 

Feel welcome if there's any issue with my first _tap_

**Comment by yschimke** [comment]
Worked fine for me!
