### ISSUE TITLE
Feature Suggestion: iTerm support (display images inline and open other files)

### ISSUE THREAD

**Issue by yschimke** [holgerbrandl/kscript#51]
Feel free to steal code from 

https://github.com/yschimke/oksocial-output/blob/master/src/main/java/com/baulsupp/oksocial/output/iterm/ItermOutputHandler.kt
https://github.com/yschimke/oksocial-output/blob/master/src/main/java/com/baulsupp/oksocial/output/OsxOutputHandler.kt

Features 
- show previews inline
- open other files in preview etc

![image](https://user-images.githubusercontent.com/231923/32402847-cd987c02-c0e9-11e7-847c-c962be0c0844.png)

**Comment by holgerbrandl** [comment]
kscript is not a REPL/interactive shell but a rather a script interpreter, so how/where would this fit it?

Even so,  this looks interesting. Is it possible to similar image inlining in the regular macos terminal as well? Is it feasible to do something similar under linux (e.g. ubuntu)?

**Comment by yschimke** [comment]
I'm not using it as a repl.  I'm moving some examples I wrote in Java/jjs to kscript

e.g. https://twitter.com/yschimke/status/858345997822513158

![image](https://pbs.twimg.com/media/C-l0-76WAAIoVwv.jpg:large)

**Comment by holgerbrandl** [comment]
I see, nice idea. Shouldn't this work already if you declare the oksocial library as a script dependency?

**Comment by yschimke** [comment]
Yep, that's why I put it as "Feature Suggestion", feel free to close.
