### ISSUE TITLE
Support API example not working with kscript 2.1.0

### ISSUE THREAD

**Issue by lwhansen** [holgerbrandl/kscript#52]
I get errors trying inline example with kscript 2.1.0 and kotlin 1.1.51:

cat some_flights.tsv | kscript 'stdin.filter { "^de0[-0]*".toRegex().matches(it) }.map { it + "foo:" }.print()'

returns:

[ERROR] compilation of 'stdin.filter { "^de0[-0]*".toRegex().matches(it) }.map { it + "foo:" }.print()' failed
/tmp/tmp6868296498685827648.tmp/scriptlet.b36b82442f201d8e.kts:1:1: error: cannot access 'stdin': it is private in file
stdin.filter { "^de0[-0]*".toRegex().matches(it) }.map { it + "foo:" }.print()
^
/tmp/tmp6868296498685827648.tmp/scriptlet.b36b82442f201d8e.kts:1:7: error: unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public inline fun <T> Array<out ???>.filter(predicate: (???) -> Boolean): List<???> defined in kotlin.collections
public inline fun BooleanArray.filter(predicate: (Boolean) -> Boolean): List<Boolean> defined in kotlin.collections
public inline fun ByteArray.filter(predicate: (Byte) -> Boolean): List<Byte> defined in kotlin.collections
public inline fun CharArray.filter(predicate: (Char) -> Boolean): List<Char> defined in kotlin.collections
public inline fun CharSequence.filter(predicate: (Char) -> Boolean): CharSequence defined in kotlin.text
public inline fun DoubleArray.filter(predicate: (Double) -> Boolean): List<Double> defined in kotlin.collections
public inline fun FloatArray.filter(predicate: (Float) -> Boolean): List<Float> defined in kotlin.collections
public inline fun IntArray.filter(predicate: (Int) -> Boolean): List<Int> defined in kotlin.collections
public inline fun LongArray.filter(predicate: (Long) -> Boolean): List<Long> defined in kotlin.collections
public inline fun ShortArray.filter(predicate: (Short) -> Boolean): List<Short> defined in kotlin.collections
public inline fun String.filter(predicate: (Char) -> Boolean): String defined in kotlin.text
public inline fun <T> Iterable<???>.filter(predicate: (???) -> Boolean): List<???> defined in kotlin.collections
public inline fun <K, V> Map<out ???, ???>.filter(predicate: (Map.Entry<???, ???>) -> Boolean): Map<???, ???> defined in kotlin.collections
public fun <T> Sequence<???>.filter(predicate: (???) -> Boolean): Sequence<???> defined in kotlin.sequences
stdin.filter { "^de0[-0]*".toRegex().matches(it) }.map { it + "foo:" }.print()
      ^
/tmp/tmp6868296498685827648.tmp/scriptlet.b36b82442f201d8e.kts:1:46: error: unresolved reference: it
stdin.filter { "^de0[-0]*".toRegex().matches(it) }.map { it + "foo:" }.print()
                                             ^
/tmp/tmp6868296498685827648.tmp/scriptlet.b36b82442f201d8e.kts:1:58: error: unresolved reference: it
stdin.filter { "^de0[-0]*".toRegex().matches(it) }.map { it + "foo:" }.print()

**Comment by holgerbrandl** [comment]
The docs were/are slightly outdated. I'll fix them asap. You need to add a -t or --text argument to enable the text-processing support API

**Comment by lwhansen** [comment]
Thanks
