### ISSUE TITLE
enums

### ISSUE THREAD

**Issue by ilanpillemer** [holgerbrandl/kscript#61]
Although I have included the class with the enums, I cannot import the <class_name>.* in the script.

included class
```
enum class BType {
    DECIMAL,
    TIMESTAMP
} 
```
But in kts file 
`import BType.*`
does not work.

**Comment by holgerbrandl** [comment]
Like in 
![image](https://user-images.githubusercontent.com/200952/32899393-25bc949e-caeb-11e7-8811-79be6b33f0a1.png)
?
Seems to work fine for me. Could you detail out a bit further what goes wrong by providing a more complete self-contained example?

**Comment by ilanpillemer** [comment]
I dont want to type "BType", just "DECIMAL"

**Comment by holgerbrandl** [comment]
Indeed, imports need to come first, but the enum impl comes later. I guess all you could do is
```
enum class BType {
    DECIMAL,
    TIMESTAMP
}
val DECIMAL = BType.DECIMAL
val TIMESTAMP = BType.TIMESTAMP

print(DECIMAL)
```
I'm closing the ticket since it's more kotlin-lang related and not kscript specific. You could ask in the kotlin slack.

**Comment by ilanpillemer** [comment]
well actually this is kscript specifc as I am writing a DSL and the script is the DSL.
So need to make sure all irrelevant noise is not present.
I guess I could fork kscript?
