### ISSUE TITLE
SDK fails to install v 2.2.x on Linux 64

### ISSUE THREAD

**Issue by mfreeman-xtivia** [holgerbrandl/kscript#64]
Attempting to use sdk to update from version 2.1 to any 2.2.x results in the following error:
 
"kscript binaries are incompatible with Linux64"

This running in Windows WSL, so "uname -a" reports

Linux [hostname]4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by holgerbrandl** [comment]
When does the error occur: During the sdk installation or when running kscript? Can you install other tools with sdkman on Windows WSL?

**Comment by mfreeman-xtivia** [comment]
The error occurs during sdk install e.g. "sdk install kscript v2.2.0"

And yes, I have installed other tools with sdkman in WSL, including having installed kscript 2.1.1 itself with it previously

**Comment by marc0der** [comment]
Could we change the title of this issue to reflect that it fails on Windows WSL?  Just tested it and installs perfectly on native Linux environments.

**Comment by mfreeman-xtivia** [comment]
We can close this---been using nvm for too long, I guess.  "sdk install kscript v2.2.0" is not correct and should be "sdk install kscript 2.2.0" (no v as in version needed). Once corrected, everything works fine. Thanks
