### ISSUE TITLE
it should die more gracefully if `idea` is not present when using `kscript --idea`

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/kscript#66]

**Comment by gps** [comment]
Would be great to have a similar warning if maven is not installed as well (right now, it just says failed to fetch dependencies, and to file an issue).

**Comment by holgerbrandl** [comment]
You're so right @gps, same with `javac` and `jar`. But since every check requires an own process we may skip checking `jar` for now which typically comes with javac anyway.

Just for me as a reminder: no need for checking `kotlin` because kscript would not run otherwise.
