### ISSUE TITLE
Document dependencies of kscript

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#69]
Open issue-snippet from prior issue --> 

Q: How does one determine the dependencies of kscript itself ?
Its not at all obvious -- if you start with a typical dev system then everything is there, but then *everthing* is already there.
Try starting with a minimal docker container (my current favorite is amazonlinux - but any minimal will do).

A) 'obviously' a JVM is needed -- jdk or jre ?  
B) 'obviously' kotlinc is needed --> only obvious by reading the code actually - a plausible implementation could embed kotlinc -- so it is a guess.
C) obviously (no quotes),  kscript itself 

Then what -- being a 'scripting' language not all dependencies appear as instant errors.

Some features need maven -- and The Maven Universe
What else ? 

With the goal of producing a minimal install - suggest that the features enumerate the dependancies, so that if, for example, I dont *want* to install maven Id like to know what features wont work -- then I can choose if I need those or not.
 
Some of the dependencies may be able to be produced as a byproduct of the kscript build, some may not.  

Presumably most features are independent - e.g.  specifying kscript dependency by maven coordinates *probably* requires maven (?) but specifying by absolute URL *probably* does not (?) 

The side effect of doing such a great job at hiding the details -- are the the details are well hidden :)

**Comment by holgerbrandl** [comment]
Indeed, this should be made more clear. Maybe not right on the main README but at least in the (emerging) user_guide.md


Always needed when running `kscript`:
* `jar` (not sure if this is part of jre or just jdk; 
* `kotlinc` to compile the script and a wrapper class
* `kotlin` to run the user application (and to run itself) which itself requires a jre
* `bash` is used for the launcher 

optional dependencies
* `mvn` to resolve dependencies if present in the script

Actually the repo contains a docker container spec that details out what is needed to run kscript. See https://github.com/holgerbrandl/kscript/blob/master/misc/Dockerfile

Feel welcome if you specific ideas to shed more and better light on the `kscript` execution model.
