### ISSUE TITLE
symlink of kscript -> install-dir/kscript/bin/kscript does not work

### ISSUE THREAD

**Issue by DALDEI** [holgerbrandl/kscript#70]
Typical installation of a package may use symlinks to the binaries, example 'alternatives' command does this. 

does not work for kscript

install to /usr/local/kscript-2.2.1
```

$ ln -s /usr/local/kscript-2.2.1/bin/kscript /usr/local/bin/kscript
$ kscript 'println("hi")'
error: could not find or load main class kscript.app.KscriptKt
```

unfortunately kotlin doesn't like my usual hack of making a shadow exe jar by concatenating a script header before the jar  -- java -jar works but not kotlin --- (

For kscript fortunately there is only 1 more file (the .jar) so putting the .jar in /usr/local/bin  fixes things.
That is not 'aesthetically pleasing'  -- but in reality the biggest pain point is figuring out the solution.
A possible solution is similar to the CYGWIN hack -- to use readlink or realpath -- and while your at it could optimize out the use of dirname so theres no additional overhead  (left as an excrsize ttr) 

Note: kotlin binary itself works fine as a symlink

**Comment by holgerbrandl** [comment]
I've committed a patch for that problem yesterday. It's not yet released, but maybe you could check out the repo and try it?

**Comment by holgerbrandl** [comment]
Not yet released but fixed in master.
