### ISSUE TITLE
Too slow

### ISSUE THREAD

**Issue by 4ntoine** [holgerbrandl/kscript#74]
Thanks for the awesome tool! Unfortunately it's too slow at the moment (that i was afraid of):

> /tmp/ksc asmirnov$cat ./hw.kts 
> #!/usr/bin/env kscript
> 
> println("Hello from Kotlin")
> for (arg in args) {
>     println("arg: $arg")
> }/tmp/ksc asmirnov$time ./hw.kts 1 2 3
> Hello from Kotlin
> arg: 1
> arg: 2
> arg: 3
> 
> real	0m4.002s
> user	0m7.557s
> sys	0m0.526s
> /tmp/ksc asmirnov$time ./hw.kts 1 2 3
> Hello from Kotlin
> arg: 1
> arg: 2
> arg: 3
> 
> real	0m0.626s
> user	0m0.633s
> sys	0m0.117s

MBP with 16GB of RAM, SSD, Java 8, Sierra.
Any chance to make it faster?

**Comment by 4ntoine** [comment]
BTW did you try kotlin/native 0.4?

**Comment by holgerbrandl** [comment]
The compiler is good to go, but I'd need some File API.

**Comment by holgerbrandl** [comment]
I'll close this for now because this not going to change in the next year or so.
