### ISSUE TITLE
Custom interpreter preamble needs to be consolidated with rest of script

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/kscript#77]
It would be sufficient to simply process it like a `@file:Inlcude` containing script

Test needs to be adjusted as well.

See 
https://github.com/holgerbrandl/kscript/blob/e26c02612f8213b147b27d4f44f115bd44f45ca1/src/main/kotlin/kscript/app/Kscript.kt#L452

**Comment by ilanpillemer** [comment]
Can includes include deps?

**Comment by holgerbrandl** [comment]
Yes they can, but it's unrelated to this ticket. But no `includes` within `include`s at the moment because it was tagged YAGNI. ;-) 

In here, the problem is that at the moment the user-script that is using the custom interpreter can not declare additional dependencies via `@file:DependsOn` (or do any other annotation-driven config).  This is because `@file:*` need to come first in a `kts`/`kt` because the kotlin lang-specs require it.

The easiest fix would be to simply inject the preamble via a prepended `@Include` statement and let the consolidation logic in `kscript.app.ResolveIncludesKt#resolveIncludesInternal` take care of it, but since it can't resolve recursively anymore (->YAGNI fights back!), I need to find another way to fix it.

If you don't use annotations but rather prefer comment directives to declare includes and dependencies, this should not affect you.

**Comment by ilanpillemer** [comment]
```
kotlin (master *+) ~~> ./mm simple.kts 
[kscript] [ERROR] Failed to resolve //INCLUDE 'SemanticModel.kt'
[[kscript] [ERROR] /var/folders/cw/6_jr6ms12wgchzxj9s9kq5sm0000gn/T/tmp12949626543670535068.tmp/SemanticModel.kt (No such file or directory)]
```

**Comment by holgerbrandl** [comment]
You should not use quoted paths. Just 
```
//INCLUDE SemanticModel.kt
// or to emphasize the relativeness
//INCLUDE ./SemanticModel.kt
```

**Comment by holgerbrandl** [comment]
I've also created  a gitter to chat about how-to-use under https://gitter.im/holgerbrandl/kscript?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge
