### ISSUE TITLE
Symlinking does not work correctly with --idea and relative paths.

### ISSUE THREAD

**Issue by Playacem** [holgerbrandl/kscript#82]
Running `kscript --idea script.kts` results in a broken symlink file that links to `script.kts`. This makes the opened IntelliJ instance unusable, as no script file can be found. 

The [mentioned StackOverflow question](https://stackoverflow.com/questions/17926459/creating-a-symbolic-link-with-java) suggests using absolute Paths.

**Comment by gtoast** [comment]
Can confirm this. Relative path resulted in broken sym link. Using an absolute path to the same .kts file resulted in a valid project.

**Comment by holgerbrandl** [comment]
Thanks, not sure how I could miss it in the first place. :-|
