### ISSUE TITLE
--interactive fails unless your script contains dependencies

### ISSUE THREAD

**Issue by gtoast** [holgerbrandl/kscript#83]
--interactive complains about the classpath argument unless your script contains a dependency.  Is this expected behavior?

test.kts:
````kotlin
#!/usr/bin/env kscript

println("Hello from Kotlin!");

for (arg in args) {
  println("arg: $arg")
}
````

```
$ kscript -i test.kts
Creating REPL from scores.kts
error: no value passed for argument -classpath
info: use -help for more information
```
Add any dependency target to test.kts and --interactive succeeds. 

P.S. Thank you for all your work on this app. Makes jumping into and exploring Kotlin a breeze! And the -idea flag! So awesome!

**Comment by holgerbrandl** [comment]
No it's clearly not intended. :-)
