### ISSUE TITLE
Add Gradle wrapper to the project

### ISSUE THREAD

**Issue by gildor** [holgerbrandl/kscript#85]
Kscript uses Gradle as a build tool but doesn't provide Gradle wrapper distribution.
Is that intentionally?
Gradle Team recommends using Gradle wrapper, because 
- Easier to use (you shouldn't download standalone Gradle to contribute)
- Reproducible builds. If you ship Gradle wrapper with source code you always use compatible version of Gradle with particular version of sources

If you agree to add Gradle wrapper to the project, I can contribute

**Comment by holgerbrandl** [comment]
Do you mean to the dev-setup (i.e. to build kscript itself) or to the user installer? The former seems fine, for the latter I would not be so sure about how it would fit in.

**Comment by gildor** [comment]
I'm talking about kscript itself and kscript developer setup.

**Comment by holgerbrandl** [comment]
Feel welcome to add the wrapper. We should update the README and the travis config to make sure that it is actually used.
