### ISSUE TITLE
it fails to correcly forward empty and space-containing arguments to the user process

### ISSUE THREAD

**Issue by holgerbrandl** [holgerbrandl/kscript#98]
```
kscript "println(args.size)" "" foo bar
```
should be 3 but 2 is reported

```
kscript "println(args.size)" "foo bar"
```
should be 1 but is 2

**Comment by holgerbrandl** [comment]
Even with arg-quoting it fails to forward correctly when using exec. Most likely because of https://unix.stackexchange.com/questions/160333/how-can-i-run-a-bash-variable-as-a-command-exactly-without-additional-quotation

**Comment by holgerbrandl** [comment]
Also useful https://yakking.branchable.com/posts/whitespace-safety/

**Comment by holgerbrandl** [comment]
No clue how to fix it, feel welcome to contribute some ideas here!

**Comment by ilanpillemer** [comment]
Still stuck with #94
