### ISSUE TITLE
can //INCLUDE  support directory?

### ISSUE THREAD

**Issue by howawong** [holgerbrandl/kscript#99]
Currently I can only import files only line by line? Is it possible to include all kt/kts files in a directory?

**Comment by holgerbrandl** [comment]
No this is not possible at the moment. I'd suggest to use a dependency where possible. It's much faster than compiling directories with multiple files along with the script of interest.

Also a fix does not seem straighforward to me, but feel welcome to submit a PR (including impl and tests). See `kscript.app.ResolveIncludesKt#resolveIncludes`
